### PR TITLE
C++: Prevent `AliasedVirtualVariable` from overlapping string literals

### PR DESCRIPTION
**Pull request by dbartol**
We were hitting a combinatorial explosion in `hasDefinitionAtRank` for functions that contain a large number of string literals. The problem was that every `Chi` instruction for `AliasedVirtualVariable` was treated as a definition of every string literal. We already mark string literals as `isReadOnly()`, but we were allowing `AliasedVirtualVariable` to define read-only locations so that the `AliasedDefinition` instruction would provide the initial definition for all string literals.

To fix this, I've introduced the new `InitializeNonLocal` instruction, which is inserted in the prologue of every function right after `AliasedDefinition`. It provides the initial definition for every non-stack memory location, including read-only locations, but is never written to anywhere else. It is the conterpart of the `AliasedUse` instruction in the function epilogue, which represents the use of all non-stack memory after the function returns. I considered renaming `AliasedUse` to `ReturnNonLocal`, to match the `InitializeXXX`/`ReturnXXX` pattern we already use for parameters and indirections, but held off to avoid unnecessary churn. Any thoughts on whether I should make this name change?

This change has a significant speedup in evaluation time for a few of our troublesome databases:
`attnam/ivan`: 13%
`awslabs/s2n`: 26%
`SinaMostafanejad/OpenRDM`: 7%
`zcoinofficial/zcoin`: 8%

### CODE REVIEW

**Comment by rdmarsh2** [comment]
Why do we need to introduce `InitializeNonLocal` rather than allowing `AliasedDefinition` but not its chi nodes to define read-only memory locations?

**Comment by dbartol** [comment]
@rdmarsh2 Mostly because a bunch of the pieces I needed to do it the way I did were already available. We already had the notions of a read-only `MemoryLocation` and a special `MemoryLocation` that could provide a definition for a read-only location. We already had a `MemoryLocation` corresponding to all non-local memory, which is used on the `AliasedUse` instruction. All we needed to do was introduce a definition of that `AllNonLocalMemory` location at the beginning of the function, make that the definition that could define the read-only locations, and everything fell into place.

To do it the other way would be a bit more work, but nothing drastic. We'd need to introduce a new `MemoryLocation` representing the initialization def of all aliased memory (essentially, `AliasedVirtualVariable` except with `canDefineReadOnly()` set), make that an exactly-overlapping member of `AliasedVirtualVariable`, add a new `MemoryAccessKind` to represent that location, and then make `AliasedDefinition` return that as its `getResultMemoryAccess()`. That doesn't seem like much more work that my current approach.

I do like how my current approach parallels how we handle indirect parameters, by having an `InitXXX` instruction in the prologue and a corresponding `ReturnXXX` in the epilogue. Those two instructions give us a place to connect interprocedural data/taint flow edges for flow through global or static variables. That may just be architecture astronautics on my part though.

**Comment by rdmarsh2** [comment]
>I do like how my current approach parallels how we handle indirect parameters, by having an InitXXX instruction in the prologue and a corresponding ReturnXXX in the epilogue. Those two instructions give us a place to connect interprocedural data/taint flow edges for flow through global or static variables. That may just be architecture astronautics on my part though.

That's a plausible argument for this approach, and you've already done the work for it, so we can just go forward with it.

You'll need to update the IR GVN test, and the added instruction means this is going to conflict with most other PRs that touch IR generation anyways, so I'd say to do the rename now as well.

**Comment by jbj** [comment]
> I considered renaming AliasedUse to ReturnNonLocal, to match the InitializeXXX/ReturnXXX pattern we already use for parameters and indirections, but held off to avoid unnecessary churn. Any thoughts on whether I should make this name change?

Let's keep that churn out of this PR. I'd be happy with more consistent names down the line, but I'm not a fan of the `Return` prefix. It has already confused me before because I thought it was related to the return value of the function.

**Comment by dbartol** [comment]
@jbj I've added a test case to `ssa.cpp` that best illustrates the change. Without this PR, the definition of the `Load` would have been connected to the `Phi` at the beginning of block 3, rather than to the `InitializeNonLocal` instruction,

**Pull request merged**
