### PR TITLE
CPP: Rename/relocate some queries and libraries

### PR DESCRIPTION
**Pull request by geoffw0**
These are all recently contributed files, so the aim is to rename them now before they become part of a release and it would be potentially more disruptive to rename them.

Reasons are given on each commit - please discuss if you disagree with anything or have better suggestions.

### CODE REVIEW

**Comment by geoffw0** [comment]
> 3. A library named semmle.code.cpp.controlflow.VirtualDispatch is likely to be considered the official C++ virtual dispatch library. I'm not very fond of that since it's received no testing for performance or correctness at scale. I'd prefer placing it in the same directory as the one query that uses it. Alternatively, name it semmle.code.cpp.controlflow.VirtualDispatchOverapproximationPrototype.
> 4. The C# and Java libraries use semmle.code.csharp.dispatch.Dispatch and semmle.code.java.dispatch.VirtualDispatch respectively, so I'll argue for keeping that directory even if it only has a single file.

Fair enough.  So would you prefer `semmle.code.cpp.dispatch.VirtualDispatch` (i.e. what it was before) or perhaps `semmle.code.cpp.dispatch.VirtualDispatchPrototype`?

**Comment by jbj** [comment]
I prefer `semmle.code.cpp.dispatch.VirtualDispatchPrototype`. Then there's room for adding a `semmle.code.cpp.dispatch.VirtualDispatch` library later, without having to consider backwards compatibility.

**Comment by geoffw0** [comment]
> 1. The name BufferAccess.qll is too generic for what this library does. It doesn't seem to be a library that's intended to be used in other queries. I suggest inlining it into the one query that uses it. We can later fold it into existing taint-tracking rules.

Good idea.  I wasn't keen on that file (particularly as we already have a fairly general purpose `BufferAccess` library), but I hadn't realized it could be removed (inlined into a single query) so easily.

> 2. To follow our usual naming conventions, the NtohlArrayGood.cpp file should be named NtohlArrayNoBound-good.cpp. Same for Bad.

Seems reasonable, done.

**Comment by geoffw0** [comment]
> I prefer semmle.code.cpp.dispatch.VirtualDispatchPrototype.

Done.

All comments addressed.

**Comment by rdmarsh2** [comment]
> The name BufferAccess.qll is too generic for what this library does. It doesn't seem to be a library that's intended to be used in other queries. I suggest inlining it into the one query that uses it. We can later fold it into existing taint-tracking rules.

I agree that the name is too generic, but I think it will be useful to have an umbrella class for expressions that do pointer arithmetic and dereference the result either directly or by calling a library function. Right now each query that looks for overflows or tainted indexes defines its own set of sinks, and there's sometimes gaps in coverage as a result.

**Comment by geoffw0** [comment]
> I think it will be useful to have an umbrella class for expressions that do pointer arithmetic and dereference the result either directly or by calling a library function.

We already have the models library, and the (existing) `security\BufferAccess.qll` library.  There are some slight differences in coverage (e.g. I don't think we model `recv` or have an equivalent of `PointerArithmeticAccess` in `security\BufferAccess.qll` yet?), but I think `NtohlArrayNoBound.qll` can be updated to use existing libraries.

**Pull request merged**
