### PR TITLE
C#: Handle tuple patterns in `is` expressions

### PR DESCRIPTION
**Pull request by hvitved**
This PR fixes a bug where `codeql` fails with

```
Finalizing database at /tmp/db-csharp.
Running TRAP import for CodeQL database at /tmp/db-csharp...
Oops! A fatal internal error occurred.
com.semmle.util.exception.CatastrophicError: Expected '(' and not LABEL
```

The problematic TRAP file looks like

```
#4946=@"{#4947=*
extractor_messages(#4947,5,"C# extractor","Object reference not set to an instance of an object.","first.GetCommonRoot(last)",#4945,"   at Semmle.Extraction.TrapExtensions.WriteLabel(TextWriter trapFile, IEntity entity) in /code/ql/csharp/extractor/Semmle.Extraction/TrapExtensions.cs:line 17
   at Semmle.Extraction.TrapExtensions.WriteSubId(TextWriter trapFile, IEntity entity) in /code/ql/csharp/extractor/Semmle.Extraction/TrapExtensions.cs:line 23
   at Semmle.Extraction.CSharp.Entities.LocalVariable.WriteId(TextWriter trapFile) in /code/ql/csharp/extractor/Semmle.Extraction.CSharp/Entities/LocalVariable.cs:line 24
   at Semmle.Extraction.CachedEntity`1.WriteQuotedId(TextWriter trapFile) in /code/ql/csharp/extractor/Semmle.Extraction/Symbol.cs:line 60
   at Semmle.Extraction.ICachedEntityFactoryExtensions.DefineLabel(IEntity entity, TextWriter trapFile) in /code/ql/csharp/extractor/Semmle.Extraction/Entity.cs:line 148
   at Semmle.Extraction.Context.DefineLabel(IEntity entity, TextWriter trapFile) in /code/ql/csharp/extractor/Semmle.Extraction/Context.cs:line 72
   at Semmle.Extraction.Context.CreateEntity2[Type,Entity](ICachedEntityFactory`2 factory, Type init) in /code/ql/csharp/extractor/Semmle.Extraction/Context.cs:line 105
   at Semmle.Extraction.ICachedEntityFactoryExtensions.CreateEntity2[Type,Entity](ICachedEntityFactory`2 factory, Context cx, Type init) in /code/ql/csharp/extractor/Semmle.Extraction/Entity.cs:line 142
   at Semmle.Extraction.ICachedEntityFactoryExtensions.CreateEntity[Entity,T1,T2,T3,T4](ICachedEntityFactory`2 factory, Context cx, T1 t1, T2 t2, T3 t3, T4 t4) in /code/ql/csharp/extractor/Semmle.Extraction/Entity.cs:line 118
   at Semmle.Extraction.CSharp.Entities.LocalVariable.GetAlreadyCreated(Context cx, ISymbol local) in /code/ql/csharp/extractor/Semmle.Extraction.CSharp/Entities/LocalVariable.cs:line 61
   at Semmle.Extraction.CSharp.Entities.Expressions.Name.Create(ExpressionNodeInfo info) in /code/ql/csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/Name.cs:line 57
   at Semmle.Extraction.CSharp.Entities.Expressions.Factory.Create(ExpressionNodeInfo info) in /code/ql/csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/Factory.cs:line 141
   at Semmle.Extraction.CSharp.Entities.Expressions.ImplicitCast.Create(ExpressionNodeInfo info) in /code/ql/csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/ImplicitCast.cs:line 90
   at Semmle.Extraction.CSharp.Entities.Expression.CreateFromNode(ExpressionNodeInfo info) in /code/ql/csharp/extractor/Semmle.Extraction.CSharp/Entities/Expression.cs:line 85
   at Semmle.Extraction.CSharp.Entities.Expression.Create(Context cx, ExpressionSyntax node, IExpressionParentEntity parent, Int32 child) in /code/ql/csharp/extractor/Semmle.Extraction.CSharp/Entities/Expression.cs:line 83
   at Semmle.Extraction.CSharp.Entities.Expressions.Invocation.PopulateExpression(TextWriter trapFile) in /code/ql/csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/Invocation.cs:line 39
   at Semmle.Extraction.CSharp.Entities.Expression`1.<TryPopulate>b__3_0() in /code/ql/csharp/extractor/Semmle.Extraction.CSharp/Entities/Expression.cs:line 298
   at Semmle.Extraction.ContextExtensions.Try(Context context, SyntaxNode node, ISymbol symbol, Action a) in /code/ql/csharp/extractor/Semmle.Extraction/Context.cs:line 542")
```

The underlying issue is that `LocalVariable.WriteId` fails when `Parent` is `null`, which means that the ID is only partially written (`#4946=@"{`). This in turn happens when `GetAlreadyCreated` is called before `Create`. The fix is to factor out columns of  `localvars` into a separate predicate `localvar_info`, which contains the information that is only available when we also have the variable declaration in scope.

I have tested that my change works for the problematic code base (Roslyn).

### CODE REVIEW

**Comment by calumgrant** [comment]
Do you have the problematic source code that caused `GetAlreadyCreated()` to be called prior to `Create()`. Whenever that has happened in the past, the fix has been to reorder the sequence of operations in the extractor, perhaps with a `PopulateLater()`, in order to fix this type of problem.

**Comment by calumgrant** [comment]
We could also put a `try` `catch` into `TrapExtensions.WriteSubIdI()`, so that catastrophic `NullDereferenceExceptions` do not corrupt the trap file.

**Comment by hvitved** [comment]
> Do you have the problematic source code that caused `GetAlreadyCreated()` to be called prior to `Create()`. Whenever that has happened in the past, the fix has been to reorder the sequence of operations in the extractor, perhaps with a `PopulateLater()`, in order to fix this type of problem.

Yes, the problematic line is [here](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/Editing/ImportAdderService.cs#L277), and the TRAP file is [here](https://github.com/Semmle/ql/files/3904498/ImportAdderService.cs.trap.gz). I have added a regression test as well, which fails prior to the changes in this PR.

I think the reordering strategy is a bit fragile (this problem has bit us many times before in the past), so this is I why I wanted a different approach that is guaranteed to work in all cases. I would even argue that this change has simplified the extractor code, but that is perhaps a matter of taste.

**Comment by hvitved** [comment]
> We could also put a `try` `catch` into `TrapExtensions.WriteSubIdI()`, so that catastrophic `NullDereferenceExceptions` do not corrupt the trap file.

We could do that, but we would still have to put in some value for `X` in `{#X}` in case the entity is `null`, not sure what that should be.

**Pull request merged**
