### PR TITLE
C++: compute overlap on irvars with vvar indexes

### PR DESCRIPTION
**Pull request by rdmarsh2**
Followup to #2570. Computes the offset indexes using a rank aggregate over `VirtualVariable` and then computes overlap by joining on `IRVariable`.

### CODE REVIEW

**Comment by geoffw0** [comment]
`isCoveredOffset` seems to be a bit quicker in terms of tuple counts.  And I agree that the new code is cleaner.

The result of `count(VariableMemoryLocation def, VariableMemoryLocation use | overlappingIRVariableMemoryLocations(def, use))` changes slightly - I'd like to understand why.

**Comment by rdmarsh2** [comment]
On what snapshot? I didn't see a change when testing on s2n

**Comment by geoffw0** [comment]
It appears it doesn't differ on every project, but it does on COMBINE-lab/salmon and videolan/vlc (for example).

**Comment by rdmarsh2** [comment]
After looking into this more, it looks like some instances of `TVariableMemoryLocation` that would be `VirtualVariable`s are never generated, presumably because there is no instruction that accesses the whole virtual variable. I believe the increase in results of `overlappingIRVariableMemoryLocations` is a positive change, and there's no result changes in the sanity queries with this branch.

**Comment by jbj** [comment]
I propose we merge #2629 first and then test this PR again.

**Comment by rdmarsh2** [comment]
Now that #2629 is merged, this PR no longer changes the result of `count(VariableMemoryLocation def, VariableMemoryLocation use | overlappingIRVariableMemoryLocations(def, use))`. I'll retrigger the tests.

**Pull request merged**
