### PR TITLE
Move upgrade scripts into the qlpacks.

### PR DESCRIPTION
**Pull request by hmakholm**
This should not go in until the internal PR https://git.semmle.com/Semmle/code/pull/34929 has been merged. See that for a further explanation.

### CODE REVIEW

**Comment by hmakholm** [comment]
The internal PR is now merged.

**Comment by max-schaefer** [comment]
Looks like the check-queries Jenkins script needs to be taught to ignore the upgrade scripts. FWIW I do occasionally use "run all queries" on `ql/src`; I'll have to train myself to stop doing this now that the upgrade scripts are in there as well.

**Comment by hmakholm** [comment]
@max, is the "run all queries" you're talking about a QL4E command? I'm working on a general fix to exclude upgrades directories from all places that say "take all the .ql files in such-and-such directories".

**Comment by hmakholm** [comment]
(Sorry, wrong max pinged).

**Comment by hmakholm** [comment]
Closing in favor of the simpler https://github.com/Semmle/ql/pull/2214

**Pull request closed without merging**
