### PR TITLE
CPP: Slightly faster definitions.ql

### PR DESCRIPTION
**Pull request by geoffw0**
This is a change to definitions.qll (for definitions.ql), that splits up the complicated `definitionOf` predicate so that the optimizer can work on it a bit more easily.  The gain is only a few percent though (fairly consistent across a bunch of projects I tried).

This predicate has resisted other attempts to speed it up, such as excluding non-source elements at various points.

### CODE REVIEW

**Comment by zlaski-semmle** [comment]
I have a newbie question.  It looks like you've hoisted some disjunctions out of `definitionOf`.  Is this a viable optimization strategy generally, or does it work in just this particular case?

**Comment by geoffw0** [comment]
> Is this a viable optimization strategy generally, or does it work in just this particular case?

I don't think this is especially general, no, and the benefit in this case isn't very big either.

I recommend you read the 'Common performance pitfalls' section of https://docs.google.com/document/d/12LURUTA51n1xeuoyGHhnSNTTjIa-1LQFG2sb_i-WhNI/edit#heading=h.m77eg2mx2bf6, and perhaps begin to have a look at https://docs.google.com/presentation/d/1NhfjCmFIXin2Wi6QsU2Lw1Kc1ppUxJiHMYNZ1Wnx-30/.  The latter is pretty advanced though and might be best saved for later.

Feel free to talk to be or @jbj about any particular code you're looking to optimize.

**Comment by jbj** [comment]
Superseded by #1359.

**Comment by geoffw0** [comment]
Yep, I should get around to reviewing that today.

**Pull request closed without merging**
