### PR TITLE
JS: add type-tracking to the fs-modules and model `original-fs`

### PR DESCRIPTION
**Pull request by esbena**
The `fs` module is particularly prone to being imported in ways `DataFlow::moduleImport` does not recognize well enough. This is due to the way people implement fallbacks to other `fs` alternatives with various indirections.

See [`return require(process.versions['electron'] ? "original-fs" : "fs");`](<https://github.com/cthackers/adm-zip/blob/e116bc18df51e4e50c493cede82ae7696954b511/util/fileSystem.js#L2>) as an example.

To address this, I have added type-tracking to the `fs` modules, and allowed a bit of dataflow for the module string name.

It appears to discover a bunch of new `fs`-member accesses: <https://lgtm.com/query/1026525688262921620/>.

### CODE REVIEW

**Comment by erik-krogh** [comment]
Some of the results (e.g. [this one where they use a custom `require` function](https://lgtm.com/projects/g/adobe/brackets/snapshot/189335ff7dc73a50981e1a87a3c90b8a7a332c8c/files/test/thirdparty/jasmine-reporters/jasmine.junit_reporter.js?sort=name&dir=ASC&mode=heatmap#L186)) suggests that we could use more type-tracking for more than just the `fs` module.

**Comment by esbena** [comment]
Indeed, but I *think* we found improvements in that area to be too risky waay back, both semantically and performance-wise.
The `fs` case has fixed set of module names, so we are not going to be completely wrong with that.

**Comment by esbena** [comment]
[Evaluation](https://git.semmle.com/esben/dist-compare-reports/tree/js/more-fs-modules_1582982420143)  is uneventful.

**Comment by esbena** [comment]
@asger-semmle: do you agree with this special-case `import` strategy?

**Comment by asgerf** [comment]
Yes, sounds fine to me. I'll open an issue where we can discuss generalizations.

**Pull request merged**
