### PR TITLE
C++: Remove carriage returns from files

### PR DESCRIPTION
**Pull request by ian-semmle**
Seeing as the move to a new repo means files don't have much history, this seems like a good time to make changes that make things more consistent but which might confuse 'git blame' etc.

### CODE REVIEW

**Comment by dave-bartolomeo** [comment]
Can you update .gitattributes and .editorconfig to force all .c, .cpp, and whatever else under cpp/ql/src to be LF? There are instructions in .gitattributes for how to update everything easily.

**Comment by jbj** [comment]
Seeing as we're still quite busily hotfixing 1.18, can we postpone this until 1.18 has settled down? We could also apply the changes on the `rc/1.18` branch instead of `master`, which would solve the problem and prevent future incompatibility.

**Comment by dave-bartolomeo** [comment]
@jbj Agreed. This should either go into `rc/1.18` now, or wait until 1.18 is almost done.

**Comment by nickrolfe** [comment]
Also, it looks you branched from `next` but are targeting `master`.

**Comment by ian-semmle** [comment]
I don't think this is worth breaking the freeze for, so I'll rebase on master and fiddle with the dotfiles after the 1.18 release.

**Comment by jbj** [comment]
Superseded by #209.

**Pull request closed without merging**
