### PR TITLE
C++: IR: Ignore constant static initializers

### PR DESCRIPTION
**Pull request by jbj**
This PR task a stab at improving the performance of the IR on Wireshark. See https://github.com/github/codeql-c-analysis-team/issues/37 for context.

The three new predicates in `TranslatedElement.qll` are copied from `CFG.qll`. If we decide to move forward with this approach, we need to consider sharing that code and possibly re-implementing it with less negation.

Before this PR, there were ~26M rows in `TranslatedElement.hasInstruction`, and now there are ~16M. But the more important difference is that `SSAConstruction::DefUse::hasNonPhiDefinition` drops from ~126M rows to ~35M rows. This affects many of the subsequent predicates in the aliased SSA construction, whose row counts will now be reduced similarly.

### CODE REVIEW

**Comment by jbj** [comment]
Started https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/898/

**Comment by dbartol** [comment]
We still have a long-standing issue with how we model static locals - I believe we incorrectly just treat them as automatic locals. If we fixed that issue, would this PR still be necessary?

**Comment by dbartol** [comment]
I would expect that EDG could already tell us whether a given initializer was statically or dynamically initialized, although perhaps the extractor doesn't pass that info through into the database.

**Comment by jbj** [comment]
> We still have a long-standing issue with how we model static locals - I believe we incorrectly just treat them as automatic locals. If we fixed that issue, would this PR still be necessary?

A crude fix for that issue, where we just ignore all initializers of statics, would make this PR unnecessary. But if we want to translate the initialisers that depends on locals, then we have to identify them, which is what this PR does.

**Comment by jbj** [comment]
> I would expect that EDG could already tell us whether a given initializer was statically or dynamically initialized, although perhaps the extractor doesn't pass that info through into the database.

I think that's possible, but it's not in the db today. See the discussion that starts at https://semmle.slack.com/archives/C1ECYQUMN/p1547218571104400 and continues over the two following days. For the QL CFG, we ended up deciding that it wasn't terrible to sometimes classify too many things as not constant.

**Comment by jbj** [comment]
This PR has a great impact on Wireshark analysis times:

time_split_absolute

I've started a rebuild to see if these results are reproducible: https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/902/

**Comment by jbj** [comment]
In the rebuild, the effect on Wireshark remains clear. The effect on other projects is less clear:

time_split_absolute

**Comment by jbj** [comment]
After some design discussions with @dbartol I've found a place to put the shared code. Later we can consider extending `Expr.isConstant` to include constant aggregate literals, but the change I made here seems less invasive.

I didn't find a good way to phrase the check for constant initializers positively, so it still involves negations on both sides of a recursion. My only ideas for a positive phrasing are recursion through `forall` or using `rank` to sort and iterate through all children. Both are likely to be slow.

**Pull request merged**
