### PR TITLE
Python: Add example of re.compile missing points-to

### PR DESCRIPTION
**Pull request by RasmusWL**
@tausbn do you like the idea of having a _regressions_ folder? or should I move them somewhere else?

### CODE REVIEW

**Comment by tausbn** [comment]
Hm. The name "regressions" strikes me as slightly odd in this case:
- Do we know that this ever worked? If not, it's not really a regression.
- Would we move tests out of the directory once they start yielding the correct results?

I think the idea of having a specific place to put points-to failures is sound, though.

Also, I wonder if this _might_ be fixed by #2915 (probably not, as `re` isn't a built-in per se). This does make me wonder if we're missing something similar in the interface between C and Python modules.

**Comment by tausbn** [comment]
Hm. The name "regressions" strikes me as slightly odd in this case:
- Do we know that this ever worked? If not, it's not really a regression.
- Would we move tests out of the directory once they start yielding the correct results?

I think the idea of having a specific place to put points-to failures is sound, though.

Also, I wonder if this _might_ be fixed by #2915 (probably not, as `re` isn't a built-in per se). This does make me wonder if we're missing something similar in the interface between C and Python modules.

**Comment by tausbn** [comment]
Hm. The name "regressions" strikes me as slightly odd in this case:
- Do we know that this ever worked? If not, it's not really a regression.
- Would we move tests out of the directory once they start yielding the correct results?

I think the idea of having a specific place to put points-to failures is sound, though.

Also, I wonder if this _might_ be fixed by #2915 (probably not, as `re` isn't a built-in per se). This does make me wonder if we're missing something similar in the interface between C and Python modules.

**Comment by RasmusWL** [comment]
I moved things around as we discussed (and did a nasty force-push, since that still felt like the right thing to do).

I also added an other example I had lying around (oh man, messing up the PR name soo much :frowning_face: ) -- I tried using #2915 on this as well, but no luck

**Pull request merged**
