### PR TITLE
Java/C++/C#: Improve performance of data flow with fields.

### PR DESCRIPTION
**Pull request by aschackmull**
The first pruning step is usually the performance bottleneck, so making that as fast as possible improves overall performance even if the later steps have to inspect a few more nodes.

### CODE REVIEW

**Comment by hvitved** [comment]
Could we perhaps hold this back until https://github.com/Semmle/ql/pull/1761 is merged?

**Comment by hvitved** [comment]
> Could we perhaps hold this back until #1761 is merged?

It has been merged now, so can I ask you to rebase? Then I will run a dist-compare for C# over the weekend.

**Comment by aschackmull** [comment]
Rebased.

**Comment by aschackmull** [comment]
Btw. testing locally on jdk8 with a few different configurations this has been a clear consistent improvement in wall-clock time (using 8 threads), and the number of additional visited nodes have only gone up slightly in the first two pruning steps.

**Comment by hvitved** [comment]
The [dist-compare](https://git.semmle.com/gist/tom/bbbf9b85ebc06c463459153fb8e2e456) report for C# shows no change in performance for our benchmark projects. Happy to merge as this simplifies the code anyway.

**Pull request merged**
