### PR TITLE
docs: add CODEOWNERS entries and rename `ql-documentation` > `language`

### PR DESCRIPTION
**Pull request by jf205**
This PR adds a few codeowners entries so that the relevant doc team member is pinged when PRs are created that affect qhelp files for the relevant language. I think I have the added correct github usernames and languages, but please have a quick check.

@felicity-semmle I have also renamed the `ql-documentation` folder to `language` (as discussed) and added a codeowners entry to notify us for changes in that folder.

### CODE REVIEW

**Comment by felicity-semmle** [comment]
Changes all LGTM. Thanks.

**Comment by felicity-semmle** [comment]
@mc - are you happy with this addition of you as a codeowner for JavaScript qhelp files?

**Comment by mc** [comment]
no, I am not.

**Comment by felicity-semmle** [comment]
Rico Gloeckner, my apologies. I got mixed up between repositories and mentioned entirely the wrong person. I meant to ping @mc-semmle.

**Comment by mc-semmle** [comment]
Thanks @jf205, could you add me as a CODEOWNER for the review of qhelp for COBOL? Thanks.

**Comment by jf205** [comment]
Thanks @mc-semmle. COBOL doesn't live in this repo at the moment.

**Comment by mc-semmle** [comment]
Oh ok, nothing to do then. Thanks 👍

**Pull request merged**
