### PR TITLE
C++: Fix `cpp/new-free-mismatch` false positives

### PR DESCRIPTION
**Pull request by geoffw0**
There were four new false positives for `cpp/new-free-mismatch` in `g/abseil/abseil-cpp`.  The issue was that calls to `allocator new` were being misrecognized as `malloc`-style allocations because they were function calls.

I've added test cases and tidied some things up as I went along, including deprecating another part of the legacy wrapper `alloc.qll` (something I've been meaning to get around to).

I'm thinking about the next step being wrapping the concept of an allocation `kind` (`"malloc"`, `"new"`, `"new[]"`) into the models themselves so that we can simplify this and similar code.  Perhaps we should also create additional `kind`s for some of the more exotic allocators, so that we can detect more kinds of mismatches.

### CODE REVIEW

**Comment by rdmarsh2** [comment]
The QLDoc check is failing because this is exposing the `model/implementation` qlls. I think importing those privately would be OK.
LGTM otherwise.

I think moving the matching into the models is a good idea, but I might have the model make the decision about specific functions or expressions rather than using strings. In any case, we should probably talk about it in an issue rather than a PR.

**Comment by geoffw0** [comment]
I've added QLDoc to the top of those files.  It's fairly minimal, but points users to the files in `interfaces` that are a better starting point.

**Comment by jbj** [comment]
qlformat failed :-/

**Comment by geoffw0** [comment]
Sorry about that.  Should pass this time...

**Pull request merged**
