### PR TITLE
JS: support 'this' as the root of an access path

### PR DESCRIPTION
**Pull request by asger-semmle**
Allows for sanitizers of form
```javascript
if (isSafe(this.foo.bar)) {
  let value = this.foo.bar;
}
```
Will start an evaluation when workers are ready again.

### CODE REVIEW

**Comment by esben-semmle** [comment]
I like this capability. 
I can vaguely recall some instances where `this` is aliased to another variable, could you check if we could squeeze that in here as well?

```js
function m () {
  var self = this;
  if ( isSafe(self.foo.bar)) { 
    // ...
   self.foo.bar
    // ...
 }

  function someClosure() { // <-- motivation for the self-alias. I think.
    // ...
  }
}
```

**Comment by xiemaisi** [comment]
Needs conflict resolution.

**Comment by xiemaisi** [comment]
Have you had a chance to start an evaluation yet?

**Comment by asger-semmle** [comment]
The first evaluation failed, so I'm starting another one.

**Comment by asger-semmle** [comment]
[Evaluation](https://git.semmle.com/asger/dist-compare-reports/tree/this-access-path_1547765626497) looks fine.

**Comment by xiemaisi** [comment]
Great, happy to merge once you've resolved the conflict.

**Comment by asger-semmle** [comment]
The failures look unrelated. Anyone want to merge this?

**Pull request merged**
