### PR TITLE
JavaScript: Teach autobuilder not to extract `node_modules` and `bower_components` folders.

### PR DESCRIPTION
**Pull request by max-schaefer**

### CODE REVIEW

**Comment by asger-semmle** [comment]
Nice!

Perhaps we should run an short evaluation for some extra test coverage?

**Comment by max-schaefer** [comment]
Good plan; I'll set something off to run overnight.

**Comment by max-schaefer** [comment]
redo failed

**Comment by max-schaefer** [comment]
[Here](https://git.semmle.com/max/dist-compare-reports/blob/master/js/autobuilder-exclude-node_modules/report.md) (internal link) is a simplified report of a dist-compare with this PR on all projects that have a `node_modules` or `bower_components` folder. I have verified that the folders are excluded as expected.

The original report was obviously rather lengthy, so I have cut away all results in `node_modules` folders. This leaves five results that go away and four new results. None of them are particularly interesting, except for the last one which involves some rather entertaining tracking through callbacks. It is, however, not relevant for LGTM.com since it is in a part of `node` that we exclude, and moreover in test code.

So, on the whole I think the dist-compare report shows that this is a safe change to make.

**Pull request merged**
