### PR TITLE
JS: Type tracking through imports

### PR DESCRIPTION
**Pull request by asger-semmle**
Due to a discrepancy between the data flow graph and the type inference, type tracking through named imports did not work. For example, for
```js
import { Foo } from "./foo"
```
the data flow graph used the SSA definition of `Foo` as the `PropRead` and `SourceNode`, whereas the type inference uses the `ValueNode` corresponding to the `ImportSpecifier` as the `AnalyzedPropertyRead`. This means the `propertyFlowStep` induced by the type inference did not end in a `SourceNode`, which blocked big-step type tracking.

This changes the data flow graph to use the `ValueNode` instead of the SSA definition node as the `PropRead` and `SourceNode`.

The [evaluation](https://git.semmle.com/asger/dist-compare-reports/tree/type-tracking-through-imports_1567590363327) looks very good, there's even a perf win which at first seemed too good to be true, but AFAICT we just got lucky with the optimizer here. It did reveal some FPs which I've addressed in the last two commits.

### CODE REVIEW

**Comment by asger-semmle** [comment]
> Could you briefly comment on why you chose to fix this by changing the data-flow graph instead of the type inference

It's just incredibly difficult to make changes to the type inference without breaking other things in the process. It would be a good idea to unify the treatment of import specifiers, but there are other branches blocked on this PR and I'd rather not block them much longer.

> I'm wondering about the one concerning isExperimentOn, since that doesn't seem to involve any ambient definitions.

Although not a very interesting result, it seems to be a TP.

**Comment by asger-semmle** [comment]
Based on the failing tests, it looks like I can't postpone dealing with the other kinds of import specifiers. I'm running another eval with a proposed fix.

**Comment by asger-semmle** [comment]
I've changed it so `ImportSpecifiers` are treated more uniformly: the ValueNode is the `SourceNode`, not the SSA node.

[Evaluation](https://git.semmle.com/asger/dist-compare-reports/tree/type-tracking-through-imports_1567694807684) and [re-run on the slowest ones](https://git.semmle.com/asger/dist-compare-reports/tree/type-tracking-through-imports_1567703911916) shows that some of the initial perf win has waned a bit, but still looks good. The two perf big outliers could not be reproduced so I'm inclined to blame general perf flakiness. I did download `verbose.log` from elagabalus while the re-run evaluation was running, which might explain the big swing in `duktape`.

**Comment by xiemaisi** [comment]
LGTM, but has conflicts.

**Pull request merged**
