### PR TITLE
Docs: mention lgtm in qhelp style guide

### PR DESCRIPTION
**Pull request by jf205**
I guess we can mention LGTM in the Qhelp style guide here now.
@rneatherway and @mc-semmle, this relates to https://git.semmle.com/Semmle/code/pull/31056/

### CODE REVIEW

**Comment by mc-semmle** [comment]
This is technically not incorrect but custom queries can be added to a particular project in LGTM (per-project in-repo query),  or for all your projects on LGTM (global custom queries) so perhaps best to say something in the lines of `or add a custom query to LGTM` or `add a custom query for analysis in LGTM`. Perhaps @rneatherway will prefer a different turn of phrase.

**Comment by jf205** [comment]
Good point @mc. 
Perhaps links to the help would also be useful?
Per-project queries seem to be covered in this topic: https://lgtm.com/help/lgtm/about-queries#how-do-i-add-custom-queries-to-LGTM
Are global custom queries LGTM-e only?

**Comment by mc-semmle** [comment]
@jf205 - yes sorry, I should have said that global custom queries are LGTM Enterprise only.
And what we call custom queries in LGTM.com are in fact per-project custom queries (they are referred to as per-project queries in LGTM Enteprise).
You can link to the LGTM.com topic you mention in your earlier comment or to https://lgtm.com/help/lgtm/writing-custom-queries. Depends what info you want to link to.

**Comment by jf205** [comment]
@mc I've used one of your initial recommendations to cover both per-project and global custom queries. I think that makes the most sense.

**Comment by mc** [comment]
can you stop spamming me, please?

thanks.

**Comment by jf205** [comment]
@rneatherway are you happy to merge this?

**Pull request merged**
