### PR TITLE
C++: update test output following extractor template fix

### PR DESCRIPTION
**Pull request by nickrolfe**

### CODE REVIEW

**Comment by nickrolfe** [comment]
If you add a `G<const int *>` instantiation you do indeed get a separate class with the same template argument.

**Comment by jbj** [comment]
That's probably the least bad of the two possibilities.

**Comment by jbj** [comment]
Should this be closed now?

**Comment by nickrolfe** [comment]
Yes, @ian-semmle figured out the correct extractor fix that keeps the correct output for this test.

**Pull request closed without merging**
