### PR TITLE
C++: Add test for template-params in attributes

### PR DESCRIPTION
**Pull request by matt-gretton-dann**
Test for an internal extractor change (internal PR: https://git.semmle.com/Semmle/code/pull/35209)

Note that I haven't been able to generate a test which acts on variable templates.

### CODE REVIEW

**Comment by geoffw0** [comment]
> Note that I haven't been able to generate a test which acts on variable templates.

Do you mean you haven't figured out the C++ code to do this, or there's a problem blocking such a test?

**Comment by matt-gretton-dann** [comment]
> > Note that I haven't been able to generate a test which acts on variable templates.
> 
> Do you mean you haven't figured out the C++ code to do this, or there's a problem blocking such a test?

I haven't been able to write valid C++ code to exercise this.

**Comment by jbj** [comment]
Have you considered putting this test in the `extractor_tests` directory of the internal repo? Then you won't need a submodule update.

**Comment by matt-gretton-dann** [comment]
Following discussion dropping this QL PR - the test will go in extractor-tests internally.

**Pull request closed without merging**
