### PR TITLE
CPP: Autoformat the Critical queries directory

### PR DESCRIPTION
**Pull request by geoffw0**
Continues the work stated by @jbj in https://github.com/Semmle/ql/pull/1239

The commands for this in Windows are slightly different:
```
build -j4 target/jars/qlformat.bat

find ql/cpp/ql/src/Critical -name "*.ql*" -print0 | xargs -0 target/jars/qlformat.bat --input
```

Most of the changes look like an improvement to me.  I've reverted quite a few bits though, particularly where I feel information has been lost or where `a or (b and c)` has been changed to the more ambiguously reading `a or b and c` (the former used to be our policy, we seems to have lost sight of it but regardless I struggle in good conscience commit a change I know will lead to a higher rate of errors).

### CODE REVIEW

**Comment by geoffw0** [comment]
The feeling on Slack is that the `and`-`or` thing is clear if line breaks give the `or` visual precedence, so I've gone back to what the autoformatter did with those things.  I'm not sure I'm fully on board with this, but it's at least been justified now.

**Comment by geoffw0** [comment]
Fixed merge conflict.

**Comment by jbj** [comment]
From the test failure:

```
15:20:25  [2019-04-23 14:20:25] [WARN] Unused predicate terminationProblem (/mnt/resource/jenkins/workspace/Language-Tests/CPP/ql/cpp/ql/src/Critical/OverflowCalculated.ql:32,11-29)
15:20:25  [2019-04-23 14:20:25] [ERROR] Failing due to warnings (Compiler Generated)
15:20:25  [2019-04-23 14:20:25] [ 11.8%] Found errors in ql/cpp/ql/src/Critical/OverflowCalculated.ql
```

**Comment by geoffw0** [comment]
Yep, that was a bad merge, the predicate had been deleted elsewhere.  Fixed.

**Pull request merged**
