### PR TITLE
C++: Fix performance of leap year queries

### PR DESCRIPTION
**Pull request by jbj**
The `sameBaseType` predicate was fundamentally quadratic, and this blew up on large C++ code bases. Replacing it with calls to `Type.stripType` fixes performance and does not affect the qltests. It looks like `sameBaseType` was used purely an ad hoc heuristic, so I'm not worried about the slight semantic difference between `sameBaseType` and `stripType`.

### CODE REVIEW

**Comment by jbj** [comment]
This PR reduces the time to evaluate `StructWithExactEraDate.ql` on uoip/g2opy from 6100s to no time at all.

**Comment by jbj** [comment]
Hang on, there's another performance problem: the `setter` and `getter` predicates are very slow on CoreCLR. I'll see if I can fix it and extend this PR.

**Comment by jbj** [comment]
I've added a commit to fix the CoreCLR performance problem.

**Comment by geoffw0** [comment]
I'm now working on a performance fix for `getter` and `setter`.  Are you happy for me to merge this PR now, or do you want to investigate further first?

**Comment by geoffw0** [comment]
redo failed

**Pull request merged**
