### PR TITLE
C++: support `__builtin_complex`

### PR DESCRIPTION
**Pull request by nickrolfe**

### CODE REVIEW

**Comment by geoffw0** [comment]
LGTM.  I assume it's best we wait for stats before merging this.

**Comment by geoffw0** [comment]
The test is failing.  Is this just a matter of merging at the same time as https://git.semmle.com/Semmle/code/pull/34689?

**Comment by nickrolfe** [comment]
Yes, the test in this PR is failing because it's running against a `master` extractor. If the tests pass on the internal PR, then all is well, and the two PRs should be merged at the same time.

**Comment by matt-gretton-dann** [comment]
LGTM.  But I can't approve the PR.

**Pull request merged**
