### PR TITLE
Port QLPack changes to enable IntelliSense and Go to Definition

### PR DESCRIPTION
**Pull request by dave-bartolomeo**
These changes make IntelliSense and Go to Definition work on .ql and .qll files in our test directories.

### CODE REVIEW

**Comment by rdmarsh2** [comment]
We've already crossed that bridge with #2311. We'll need to do a mergeback so `lgtm.com` will be fast-forwardable to `master`.

**Comment by adityasharad** [comment]
I think Python failures are due to a change in expected test output, which if I recall correctly is present on the master branch but not `lgtm.com`.

**Comment by adityasharad** [comment]
C++ failures looks genuine, although they are in a quarantined directory?

**Comment by rdmarsh2** [comment]
Those tests were changed to match an extractor change about a week ago, and it looks like the live lgtm.com dist is from immediately before that change. I'll rerun with the live branch instead of master.

**Pull request merged**
