### PR TITLE
Data flow: Improve join-order in `pathStep` predicate

### PR DESCRIPTION
**Pull request by hvitved**
See https://github.com/Semmle/ql/pull/2857.

### CODE REVIEW

**Comment by jbj** [comment]
```
ERROR: Could not resolve variable c (/home/jenkins/workspace/Language-Tests/Java/job/ql/java/ql/src/semmle/code/java/dataflow/internal/DataFlowImpl.qll:2270,54-55)
```

That looks like a typo: `c` should be `cc`.

**Comment by hvitved** [comment]
> That looks like a typo: `c` should be `cc`.

Thanks.

**Comment by hvitved** [comment]
Here are the profiling runs (all internal links):
- Java: https://jenkins.internal.semmle.com/job/Changes/job/Java-Differences/580/
- C++: https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/836/
- C#: https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/21/

Performance for Java is unchanged, there is a massive improvement for C++, and C# is still running (performance expected to be unchanged).

**Comment by aschackmull** [comment]
Joining `localFlowBigStep` with `getLocalCallContext` creates a potential blowup - in `ArithmeticTainted` on jdk11 the blowup is more than a factor 10, but it doesn't show up as the cost ends up dominated by other predicates.  It is, however, not the best join-order, so I've put up an alternative fix here: https://github.com/Semmle/ql/pull/2872

**Pull request closed without merging**
