### PR TITLE
TS: Fix extraction of default-exported classes and functions

### PR DESCRIPTION
**Pull request by asger-semmle**
Fixes https://github.com/Semmle/ql/issues/2051. I'm also running an evaluation just to be sure.

### CODE REVIEW

**Comment by esben-semmle** [comment]
LGTM, but @erik-krogh should be the one to sign off on this.

**Comment by esben-semmle** [comment]
(the change-notes are missing)

**Comment by asger-semmle** [comment]
> However, as one can find out by using AST explorer, it is actually a ClassDeclaration.

That doesn't really matter though. Our AST was (initially) modelled after [estree](https://github.com/estree/estree) in which a ClassDeclaration must have an identifier. I checked the spec and AFAICT there is no semantic difference.

**Comment by asger-semmle** [comment]
[Evaluation](https://git.semmle.com/asger/dist-compare-reports/tree/ts-unused-var-fix_1570472546543) on typescript.slugs looks fine.

**Pull request merged**
