### PR TITLE
CPP: Handle 'realloc' better in MemoryMayNotBeFreed.ql

### PR DESCRIPTION
**Pull request by geoffw0**
The `MemoryMayNotBeFreed.ql` query normally considers a `realloc` to be both an `alloc`, and a `free` of the old pointer.  A subtlety is that if `realloc` fails and returns `NULL` it does *not* free the old pointer.  To account for this the query considers the free of the old pointer to occur only if and when the return value is checked:
```
ptr_b = realloc(ptr_a, new_size);
if (ptr_b == 0)
{
  // handle failure (perhaps with an explicit free(ptr_a))
} else {
  // the realloc is considered to free ptr_a here
}
```
This works well up until we assign to the same variable:
```
ptr_a = realloc(ptr_a, new_size);
if (ptr_a == 0)
{
  // handle failure (which might be a bit awkward since we've just overwritten ptr_a)
} else {
  // the realloc is considered to free ptr_a here
}
```
Because now we get confused by the old vs new `ptr_a` and think the *new* allocation is being freed.

The ideal solution is probably to upgrade this query to use something like `DataFlow` rather than `LocalScopeVariableReachability` (I've created a JIRA ticket for this).

However, we need a quick fix because it's causing a regression on version 1.3 of the samate test-suite compared to the results we had on version 1.2.  The workaround is not to consider this particular pattern on `realloc` as to be a free at all.

### CODE REVIEW

**Comment by jbj** [comment]
@geoffw0 this is for 1.18, right? I've put the 1.18 milestone on it, and I've retargeted the PR to the `rc/1.18` branch.

**Comment by jbj** [comment]
I think my retargeting of the PR and my triggering of Language-Tests/CPP got a bit racy and that Jenkins is now testing `rc/1.18` of our internal repo with a submodule that's based on this PR merged into this repo's `master`. But that should be close enough that I'll accept the results.

**Comment by geoffw0** [comment]
> @geoffw0 this is for 1.18, right?

I had been hoping so, yes.

**Comment by jbj** [comment]
The test failed because (I think) this repo's `master` is broken (contains d4f9b5eb5296b4f0c6693d576db8e55964f30f27). I'll try to confirm on some other PRs that this repo's `rc/1.18` is okay.

**Comment by jbj** [comment]
The only test failures now are the ones that will be fixed by the internal PR, so I'm merging both now.

**Pull request merged**
