### PR TITLE
JavaScript: Clean up classification of sensitive variable names.

### PR DESCRIPTION
**Pull request by xiemaisi**
The diff is a little hard to read, but basically I've merged parts of `suspiciousCredentials` into `suspiciousPassword` and renamed all the `suspicious*` predicates (I don't think "suspicious" is a good term to use in this context). Note that all these predicates are marked as internal, so simply renaming them should be fine.

I've also adjusted `maybeSensitive` to eliminate a false positive noticed in https://github.com/Semmle/ql/pull/851.

The [report](https://git.semmle.com/gist/max/4645b1b3da130ee8754a24acd6e01f43) (internal link) shows that the FP was indeed eliminated, and we gained a few results for `js/clear-text-storage-of-sensitive-data`, `js/insecure-randomness` and `js/insufficient-password-hash` due to our expanded concept of what constitutes password-like data. I'd particularly appreciate feedback from @esben-semmle as the original author of these queries on whether the new results make sense.

Performance has suffered slightly, but as far as I can see the absolute slowdowns are minor. If desired I'd be happy to re-run or look more closely into the cause of the slowdown. (I'll rebase away the first and the third commit once everyone is happy, they mostly serve to document the suite I was profiling with.)

### CODE REVIEW

**Comment by esben-semmle** [comment]
The change looks fine, but the results motivate some improvements. Feel free to ignore, this is a never ending battle with the heuristics.

I think we should allow ` js/clear-text-storage-of-sensitive-data` of (some) `maybeAccountInfo` values. It seems wrong to complain about "username" being stored in a cookie. It is however great to see `js/insecure-randomness` complaining about "username".

Similarly, we may want to split `maybePassword`:
I think it is fine to hash "certificate" with a non-password algorithm in `js/insufficient-password-hash`, such a hashing is probably just a part of a protocol rather than a final transformation before persistent storage.

**Comment by xiemaisi** [comment]
Thanks for your feedback, I'll refine the model to take your suggestions into account.

**Comment by xiemaisi** [comment]
> I think we should allow ` js/clear-text-storage-of-sensitive-data` of (some) `maybeAccountInfo` values.

I agree that this sounds reasonable, but I'd like to point out that the [example in the qhelp](https://github.com/Semmle/ql/blob/master/javascript/ql/src/Security/CWE-312/examples/CleartextStorage.js) of that query is about storing an HTTP query parameter called `"AccountName"` in a cookie. Is that sufficiently different from `"username"` to make a difference, or should we just change the example?

**Comment by esben-semmle** [comment]
I think the qhelp example should be changed to store a cleartext password instead.

Here is an adjusted example with a reasonable endpoint that remembers the user's password:
```javascript
var express = require('express');

var app = express();
app.get('/remember-password', function (req, res) {
  let password = req.param("current_password");
  // BAD: Setting a cookie value with cleartext sensitive data.
  res.cookie("password", password);

```

**Comment by xiemaisi** [comment]
Thanks, @esben-semmle, I've updated the example as suggested.

A new [evaluation](https://git.semmle.com/gist/max/4645b1b3da130ee8754a24acd6e01f43#file-report2-md) with the proposed changes to `CleartextStorage` and `InsufficientPasswordHash` looks promising: performance is about the same as before, but the undesirable results are gone. Please take a look. (I've also rebased away the temporary suite used for this PR.)

**Pull request merged**
