### PR TITLE
Set Literal in QL

### PR DESCRIPTION
**Pull request by ginsbach**
This updates the language specification to explain the new [set literal](https://github.com/github/codeql-coreql-team/issues/331) language feature.

### CODE REVIEW

**Comment by alexet** [comment]
You should add a line about semantics. Basically you need to say that the values of a set literal are the values of all of the expressions.

**Comment by hmakholm** [comment]
There should also be a notation such as "supported from release 2.1.0 of the CodeQL CLI, and release 1.24 of LGTM Enterprise".

**Comment by ginsbach** [comment]
> There should also be a notation such as "supported from release 2.1.0 of the CodeQL CLI, and release 1.24 of LGTM Enterprise".

Are those the actual version numbers? I have no insight into that, so am going to assume it and put those in.

**Comment by hmakholm** [comment]
Yes, those are actual version numbers.

**Comment by jf205** [comment]
Let's get this merged today, to coincide with the release of CodeQL 2.1.0.

From a docs point of view, this looks fine. @alexet are you happy with the recent updates?

**Pull request merged**
