### PR TITLE
JS: use `query predicate` instead of `select` for testing Express

### PR DESCRIPTION
**Pull request by esben-semmle**
This speeds up the tests for Express since the tests now are compiled
together: the total test time for the affected directory was 1102 seconds
before this change, and 48.7 seconds after: a 95% time reduction.

Besides the speedup, a major difference between the two test styles is
that all selected entities now must have an explicit type, this is a
bit more verbose, but also produce slightly better tests.

I have picked a naming convention for the query predicates: they all
start with "test_" to allow for writing capitalized class names.

I expect similar improvements for other large test directories to
trickle in later.

-

Process for doing this rewrite: `cat *.ql >> Test.ql`, and then
rewrite manually from the top. This is slightly suboptimal: I can not
be entirely sure the rewritten tests are equivalent. :(

A better process would have been to rewrite each test in isolation,
and then concatenate them into one big file afterwards.

### CODE REVIEW

**Comment by esben-semmle** [comment]
https://jira.semmle.com/browse/ODASA-7810. 
In case you want more:

```
find . -type f -name \*.ql | sed -e 's+\(.*\)/.*+\1+' | sort | uniq -c | sort -rn | head -n 20
29 ./library-tests/TypeScript/TypeAnnotations
24 ./library-tests/frameworks/NodeJSLib
20 ./tutorials/Introducing the JavaScript libraries
20 ./library-tests/JSDoc
18 ./library-tests/Modules
18 ./library-tests/frameworks/koa
18 ./library-tests/Classes
16 ./library-tests/Functions
15 ./library-tests/frameworks/connect
14 ./library-tests/frameworks/restify
14 ./library-tests/frameworks/hapi
12 ./library-tests/PropWrite
11 ./library-tests/ModuleImportNodes
11 ./library-tests/Expr
11 ./library-tests/CallGraphs
10 ./library-tests/stmts
10 ./library-tests/Promises
10 ./library-tests/frameworks/ReactJS
10 ./library-tests/DOM
9 ./library-tests/frameworks/UriLibraries
```

**Comment by asger-semmle** [comment]
Could you rebase now that the failing test on master has been fixed?

**Comment by xiemaisi** [comment]
(Please don't merge just yet, I'm trying out an alternative approach I'd like to show for comparison.)

**Comment by xiemaisi** [comment]
Superseded by #1018.

**Pull request closed without merging**
