### PR TITLE
JS: whitelist quote stripping for js/incomplete-sanitization

### PR DESCRIPTION
**Pull request by esben-semmle**

### CODE REVIEW

**Comment by xiemaisi** [comment]
I assume you have verified that this doesn't lose any interesting results? I would have thought that removing quotes via `replace` is wrong if you can have escaped quotes inside the string.

**Comment by esben-semmle** [comment]
>  I would have thought that removing quotes via replace is wrong 

I do not think it is any less wrong than trying to remove other delimiter pairs this way. 

The pattern is rare though: 0 results for 236 projects (https://lgtm.com/query/5904476558374725002/).

**Comment by xiemaisi** [comment]
> I do not think it is any less wrong than trying to remove other delimiter pairs this way.

Braces are less frequently backslash-escaped, no?

**Comment by xiemaisi** [comment]
But good to hear that it doesn't happen in practice, so sounds fine to whitelist.

**Pull request merged**
