### PR TITLE
Java: Deprecate ParExpr

### PR DESCRIPTION
**Pull request by aschackmull**
With parentheses no longer in the AST we can deprecate a few things and clean up.

### CODE REVIEW

**Comment by yo-h** [comment]
Attempting to re-trigger language tests prior to merging, since they failed to run.

**Comment by aschackmull** [comment]
Rebased to solve merge conflict and autoformatted.

**Comment by yo-h** [comment]
Looks like this will also require an internal PR with a change to the internal queries:
```
05:41:38  [2020-01-30 10:41:38] [WARN] Predicate getProperExpr has been deprecated and may be removed in future (/home/jenkins/workspace/Language-Tests/Java/job/lgtm/java-queries/general/WholeIOReadNullCheck.ql:47,65-78)
05:41:38  [2020-01-30 10:41:38] [ERROR] Failing due to warnings (Compiler Generated)
05:41:38  [2020-01-30 10:41:38] [ 14.7%] Found errors in lgtm/java-queries/general/WholeIOReadNullCheck.ql
```

**Comment by aschackmull** [comment]
> Looks like this will also require an internal PR with a change to the internal queries:

It's `#36115`.

**Comment by yo-h** [comment]
Thanks, I missed that one. Retriggered tests.

**Pull request merged**
