### PR TITLE
Master-to-next merge

### PR DESCRIPTION
**Pull request by semmle-qlci**
Automatically created merge PR, pulling recent `master` changes into `next`.

### CODE REVIEW

**Comment by pavgust** [comment]
This pull request **introduces 1 alert** when merging 79e246f961f2f5712196380a80555e87a9d975b0 into 6b27dcabc567068dc9149d0aa8f74fee8cef633e - [view on LGTM.com](https://lgtm.com/projects/g/Semmle/ql/rev/pr-29ea960d51d692860aa95f97c5c0e2db31fdd673)

**new alerts:**

* 1 for Redundant ToString\(\) call

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by jbj** [comment]
Why is there no **Language-Tests/JavaScript** running?

**Comment by pavgust** [comment]
This pull request **introduces 1 alert** when merging b4f400fb23f24c835658858899faba4c14943d06 into 6b27dcabc567068dc9149d0aa8f74fee8cef633e - [view on LGTM.com](https://lgtm.com/projects/g/Semmle/ql/rev/pr-334c050ff3300e4f68b8f1382d73674055f13569)

**new alerts:**

* 1 for Redundant ToString\(\) call

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by pavgust** [comment]
This pull request **introduces 1 alert** when merging 42cf76027afd8da9c6c9f88b6afa696e5a0c8059 into 6b27dcabc567068dc9149d0aa8f74fee8cef633e - [view on LGTM.com](https://lgtm.com/projects/g/Semmle/ql/rev/pr-86a3d926eff511fd5b19360b73d2154801f4ef62)

**new alerts:**

* 1 for Redundant ToString\(\) call

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by xiemaisi** [comment]
C++ and C# tests have passed, JavaScript tests passed previously and nothing relevant has changed in the meantime, so merging.

**Pull request merged**
