### PR TITLE
JavaScript: Consolidate Express tests.

### PR DESCRIPTION
**Pull request by xiemaisi**
An alternative proposal to https://github.com/Semmle/ql/pull/999, achieving much the same effect but with a slightly less intrusive and (almost) entirely automated transformation.

I've written a little utility (based on the QL frontend) that, given a folder with `.ql` files, does the following:

  1. Replace all `select` clauses with semantically equivalent query predicates, where the name of the query predicate is the name of the `.ql` file with `test_` prepended to it.
  2. Rename all `.ql` files to `.qll` files.
  3. Create a new `tests.ql` file that imports all the `.qll` files created in the previous step.
  4. Concatenate all individual `.expected` files into one big `tests.expected` file, with the result for each query predicate preceded by its name (which is the format used by `qltest` for multi-query files).

The tool does all of these steps in one go, resulting in the second commit of this PR. To make it easier to review, however, I've then reverted that commit and added individual commits corresponding to the steps above. I'll remove those extra commits once everyone is happy.

As mentioned above, the whole process is almost entirely automated, except that the tool currently sometimes fails to construct valid qualified names for QL types (a non-trivial problem in the presence of modules). Since this only affects three of our Express tests I've opted for fixing it manually for now, but I'll try to get that sorted as well and then make the tool available to others.

### CODE REVIEW

**Comment by xiemaisi** [comment]
> Can we have a step that runs the autoformatter after the semantic transformation?

Possibly, though for this PR I'll do it manually.

I'll also fix the unnecessary import.

**Comment by xiemaisi** [comment]
Tests have passed, so unless there are objections I'd like to remove the extra commits, autoformat and fix the spurious import pointed out by @esben-semmle.

**Comment by esben-semmle** [comment]
Go ahead.

**Comment by xiemaisi** [comment]
Ping @esben-semmle.

**Pull request merged**
