### PR TITLE
CPP: Speed up AV Rule 35.ql

### PR DESCRIPTION
**Pull request by geoffw0**
Yields a little over a 10% speedup (I'd hoped for more) in AV Rule 35.ql, for most medium to large projects.

### CODE REVIEW

**Comment by jbj** [comment]
Can you provide evidence of the speed-ups in the form of relevant evaluation log snippets?

**Comment by geoffw0** [comment]
Running the query on Firefox, the original most expensive predicate:
```
	AV Rule 35.ql-2:Macro::MacroAccess::getOutermostMacroAccess#ff ....................... 10.4s (executed 214 times)
```
is gone, with a slightly smaller cost added `MacroAccess.getLocation`:
```
	AV Rule 35.ql-2:Macro::MacroAccess::getLocation#ff ........................................... 9s (executed 214 times)
```
The real benefit here appears to be cutting out a very expensive part of `Element::getLocation` (`>`'s added):
```
[2019-03-22 14:42:41] (46s) Starting to evaluate predicate Element::Element::getLocation_dispred#ff
[2019-03-22 14:42:47] (52s) Tuple counts:
                      6518     ~2%      {2} r1 = SCAN usings OUTPUT FIELDS {usings.<0>,usings.<2>}
                      6518     ~2%      {2} r2 = JOIN r1 WITH Namespace::UsingEntry#class#f ON r1.<0>=Namespace::UsingEntry#class#f.<0> OUTPUT FIELDS {r1.<0>,r1.<1>}
                      4815261  ~0%      {2} r3 = r2 \/ Declaration::Declaration::getLocation_dispred#ff
                      5159664  ~3%      {2} r4 = r3 \/ UserType::UserType::getLocation_dispred#ff
                      239292   ~0%      {2} r5 = SCAN type_decls OUTPUT FIELDS {type_decls.<0>,type_decls.<2>}
                      5398956  ~5%      {2} r6 = r4 \/ r5
                      6957613  ~36%     {2} r7 = r6 \/ Function::Function::getLocation_dispred#ff
                      1578986  ~0%      {2} r8 = SCAN fun_decls OUTPUT FIELDS {fun_decls.<0>,fun_decls.<4>}
                      8536599  ~30%     {2} r9 = r7 \/ r8
                      481670   ~0%      {2} r10 = SCAN preprocdirects OUTPUT FIELDS {preprocdirects.<0>,preprocdirects.<2>}
                      9018269  ~27%     {2} r11 = r9 \/ r10
>                     17760231 ~0%      {2} r12 = SCAN macroinvocations OUTPUT FIELDS {macroinvocations.<0>,macroinvocations.<2>}
>                     17760353 ~0%      {2} r13 = JOIN r12 WITH Macro::MacroAccess::getOutermostMacroAccess#ff_10#join_rhs ON r12.<0>=Macro::MacroAccess::getOutermostMacroAccess#ff_10#join_rhs.<0> OUTPUT FIELDS {Macro::MacroAccess::getOutermostMacroAccess#ff_10#join_rhs.<1>,r12.<1>}
>                     26778622 ~6%      {2} r14 = r11 \/ r13
                      2930160  ~1%      {2} r15 = SCAN var_decls OUTPUT FIELDS {var_decls.<0>,var_decls.<4>}
                      29708782 ~8%      {2} r16 = r14 \/ r15
                                        return r16
```
becomes:
```
[2019-03-22 14:46:56] (43s) Starting to evaluate predicate Element::Element::getLocation_dispred#ff
[2019-03-22 14:46:58] (45s) Tuple counts:
                      6518     ~2%      {2} r1 = SCAN usings OUTPUT FIELDS {usings.<0>,usings.<2>}
                      6518     ~2%      {2} r2 = JOIN r1 WITH Namespace::UsingEntry#class#f ON r1.<0>=Namespace::UsingEntry#class#f.<0> OUTPUT FIELDS {r1.<0>,r1.<1>}
                      4815261  ~0%      {2} r3 = r2 \/ Declaration::Declaration::getLocation_dispred#ff
                      5159664  ~3%      {2} r4 = r3 \/ UserType::UserType::getLocation_dispred#ff
                      239292   ~0%      {2} r5 = SCAN type_decls OUTPUT FIELDS {type_decls.<0>,type_decls.<2>}
                      5398956  ~5%      {2} r6 = r4 \/ r5
                      6957613  ~36%     {2} r7 = r6 \/ Function::Function::getLocation_dispred#ff
                      1578986  ~0%      {2} r8 = SCAN fun_decls OUTPUT FIELDS {fun_decls.<0>,fun_decls.<4>}
                      8536599  ~30%     {2} r9 = r7 \/ r8
                      481670   ~0%      {2} r10 = SCAN preprocdirects OUTPUT FIELDS {preprocdirects.<0>,preprocdirects.<2>}
                      9018269  ~27%     {2} r11 = r9 \/ r10
>                     26778500 ~6%      {2} r12 = r11 \/ Macro::MacroAccess::getLocation#ff
                      2930160  ~1%      {2} r13 = SCAN var_decls OUTPUT FIELDS {var_decls.<0>,var_decls.<4>}
                      29708660 ~8%      {2} r14 = r12 \/ r13
                                        return r14
```
I'm not all that sure what's going on here.  It's possible the same improvement can be achieved with a smaller change.

---
	
`usesMacro` is cheaper (5.1s -> 172ms) because it creates rows for vastly fewer files now.
```
[2019-03-22 14:43:11] (76s) Starting to evaluate predicate AV Rule 35::usesMacro#fb
[2019-03-22 14:43:16] (81s) Tuple counts:
                      23479299 ~0%         {2} r1 = JOIN File::HeaderFile#f WITH Element::Element::getFile_dispred#ff_10#join_rhs ON File::HeaderFile#f.<0>=Element::Element::getFile_dispred#ff_10#join_rhs.<0> OUTPUT FIELDS {Element::Element::getFile_dispred#ff_10#join_rhs.<1>,File::HeaderFile#f.<0>}
                      16381353 ~16547%     {2} r2 = JOIN r1 WITH macroinvocations ON r1.<0>=macroinvocations.<0> OUTPUT FIELDS {macroinvocations.<1>,r1.<1>}
                      16379691 ~18437%     {2} r3 = JOIN r2 WITH Macro::Macro::getName_dispred#ff ON r2.<0>=Macro::Macro::getName_dispred#ff.<0> OUTPUT FIELDS {Macro::Macro::getName_dispred#ff.<1>,r2.<1>}
                      668496   ~17071%     {2} r4 = JOIN r3 WITH project#AV Rule 35::defUndef#ff ON r3.<0>=project#AV Rule 35::defUndef#ff.<0> OUTPUT FIELDS {r3.<1>,r3.<0>}
                                           return r4
```
becomes:
```
[2019-03-22 14:47:21] (68s) Starting to evaluate predicate AV Rule 35::usesMacro#fb
[2019-03-22 14:47:21] (68s) Tuple counts:
                      677      ~3%         {1} r1 = File::HeaderFile#f AND NOT MultipleInclusion::IncludeGuardedHeader#class#f(File::HeaderFile#f.<0>)
                      750567   ~0%         {2} r2 = JOIN r1 WITH Element::Element::getFile_dispred#ff_10#join_rhs ON r1.<0>=Element::Element::getFile_dispred#ff_10#join_rhs.<0> OUTPUT FIELDS {Element::Element::getFile_dispred#ff_10#join_rhs.<1>,r1.<0>}
                      540278   ~11306%     {2} r3 = JOIN r2 WITH macroinvocations ON r2.<0>=macroinvocations.<0> OUTPUT FIELDS {macroinvocations.<1>,r2.<1>}
                      540278   ~14794%     {2} r4 = JOIN r3 WITH Macro::Macro::getName_dispred#ff ON r3.<0>=Macro::Macro::getName_dispred#ff.<0> OUTPUT FIELDS {Macro::Macro::getName_dispred#ff.<1>,r3.<1>}
                      208830   ~44923%     {2} r5 = JOIN r4 WITH project#AV Rule 35::defUndef#ff ON r4.<0>=project#AV Rule 35::defUndef#ff.<0> OUTPUT FIELDS {r4.<1>,r4.<0>}
                                           return r5
```

**Comment by jbj** [comment]
The `usesMacro` changes look significant, so let's keep those.

I'm not sold on the `MacroAccess.getLocation` changes. The speed-up from 10.4s to 9s is within the noise range for such measurements. The changed tuple counts in `Element::getLocation_dispred#ff` come because `MacroAccess.getLocation` no longer gets in-lined -- we can't in-line a recursive predicate. This particular query may now be faster, but a query that uses both `MacroAccess.getLocation` and `MacroAccess.getOutermostMacroAccess` will now be slower because there are now two 10-second recursions to be computed instead of one 10-second recursion followed by a cheap join.

To speed up `getLocation` across the whole suite, I think our best option is to make `Element.getLocation` cached. You can see in https://docs.google.com/spreadsheets/d/1J5etw38sphXWYnBOhbszsuZyyXepoYGGigIBETo7E5k/edit?pli=1#gid=1752728879 that it's recomputed many times throughout the suite.

**Comment by geoffw0** [comment]
> I'm not sold on the MacroAccess.getLocation changes.

Fair enough, I understand your reasoning.  I've removed that part of the PR now.

> To speed up getLocation across the whole suite, I think our best option is to make Element.getLocation cached.

Do you have any idea why it isn't already `cached`?  It seems like something we should have done a long time ago if it's this simple.

**Comment by jbj** [comment]
> Do you have any idea why it isn't already cached? It seems like something we should have done a long time ago if it's this simple.

It's part of https://jira.semmle.com/browse/CPP-289, and it's in perfect alignment with our OKRs for Q2. Making the change should be perfectly easy. The time-consuming part is to benchmark it.

**Pull request merged**
