### PR TITLE
CPP: Fix false positive in EmptyBlock.ql

### PR DESCRIPTION
**Pull request by geoffw0**
Fix false positive in EmptyBlock.ql where an empty block is commented after the block, all on the same line - observed https://lgtm.com/projects/g/google/re2/alerts/?mode=list&rule=cpp%2Fempty-block

### CODE REVIEW

**Comment by jbj** [comment]
The new `lineComment` predicate doesn't perform well. On Wireshark it takes 1m14s, and tuple counting shows a giant bulge in the middle:

```
[2018-10-30 08:47:20] (23s) Starting to evaluate predicate EmptyBlock::lineComment#f
[2018-10-30 08:47:20] (23s) Evaluating to sink of kind 
[2018-10-30 08:48:34] (97s) Tuple counts:
                      306488    ~2%     {1} r1 = SCAN comments OUTPUT FIELDS {comments.<2>}
                      306488    ~5%     {2} r2 = JOIN r1 WITH Location::Location::getFile_dispred#ff ON r1.<0>=Location::Location::getFile_dispred#ff.<0> OUTPUT FIELDS {r1.<0>,Location::Location::getFile_dispred#ff.<1>}
                      306488    ~0%     {3} r3 = JOIN r2 WITH Location::Location::fullLocationInfo_dispred#ffffff ON r2.<0>=Location::Location::fullLocationInfo_dispred#ffffff.<0> OUTPUT FIELDS {Location::Location::fullLocationInfo_dispred#ffffff.<2>,Location::Location::fullLocationInfo_dispred#ffffff.<2>,r2.<1>}
                      290025183 ~6%     {2} r4 = JOIN r3 WITH Location::Location::fullLocationInfo_dispred#ffffff_240#join_rhs ON r3.<0>=Location::Location::fullLocationInfo_dispred#ffffff_240#join_rhs.<0> AND r3.<1>=Location::Location::fullLocationInfo_dispred#ffffff_240#join_rhs.<1> OUTPUT FIELDS {Location::Location::fullLocationInfo_dispred#ffffff_240#join_rhs.<2>,r3.<2>}
                      392639    ~0%     {1} r5 = JOIN r4 WITH Location::Location::getFile_dispred#ff ON r4.<0>=Location::Location::getFile_dispred#ff.<0> AND r4.<1>=Location::Location::getFile_dispred#ff.<1> OUTPUT FIELDS {r4.<0>}
                      23273     ~5%     {1} r6 = JOIN r5 WITH stmts_20#join_rhs ON r5.<0>=stmts_20#join_rhs.<0> OUTPUT FIELDS {stmts_20#join_rhs.<1>}
                      3         ~0%     {1} r7 = JOIN r6 WITH EmptyBlock::emptyBlock#ff_1#join_rhs ON r6.<0>=EmptyBlock::emptyBlock#ff_1#join_rhs.<0> OUTPUT FIELDS {r6.<0>}
                                        return r7
[2018-10-30 08:48:34] (97s)  >>> Relation EmptyBlock::lineComment#f: 3 rows using 0 MB
```

Please fix. Maybe do something along the lines of https://wiki.semmle.com/display/~michaelpj/Folding.

**Comment by geoffw0** [comment]
Oh that's annoying - I tested on something quite big (`libreoffice`?) and it was quite good.  I'll look into this now.

**Comment by geoffw0** [comment]
Hmm, I can't reproduce this.  I've tried on wireshark and a bunch of other projects.  Is it possible you somehow didn't have the `Speed it up` commit?  Could you share the snapshot you used if it isn't the latest one from https://jenkins.internal.semmle.com/job/Build-Snapshot/job/wireshark/

**Comment by jbj** [comment]
That's odd. I ran my test in QL4E 1.18.0 with [this Wireshark snapshot](https://drive.google.com/drive/folders/0B5VJBNgK-GjvREQ4Y2ZicmM2VEk). The exact snapshot shouldn't matter to optimisation. I did the test by copy-pasting your modified query into the existing `EmptyBlock.ql` at 292189c1e03c94a64a5248fda8b4adb9ad9579be. It includes the speed-up fix, so the `lineComment` predicate is:

```
predicate lineComment(Block b) {
  emptyBlock(_, b) and
  exists(Location bLocation, File f, int line |
    bLocation = b.getLocation() and
    f = bLocation.getFile() and
    line = bLocation.getStartLine() and
    line = bLocation.getEndLine() and
    exists(Comment c, Location cLocation |
      cLocation = c.getLocation() and
      cLocation.getFile() = f and
      cLocation.getStartLine() = line
    )
  )
}
```

What does the optimised DIL look like for you? I get the following, which is also what you could see from my evaluation log above.

```
EmptyBlock::lineComment#f(pure unique Block::Block b) :-
  exists(pure @location call_result |
    exists(pure File::File f |
      exists(pure int line |
        exists(pure @location cLocation |
          exists(pure dontcare Comments::Comment _, pure dontcare string _1 |
            comments(_, _1, cLocation)
          ),
          Location::Location::getFile_dispred#ff(cLocation, f),
          exists(pure dontcare File::Container.class _, pure dontcare int _1,
                 pure dontcare int _2, pure dontcare int _3 |
            Location::Location::fullLocationInfo_dispred#ffffff(cLocation, _,
                                                                line, _1, _2, _3)
          )
        ),
        exists(pure int arg4, pure dontcare File::Container.class _,
               pure dontcare int _1, pure dontcare int _2 |
          Location::Location::fullLocationInfo_dispred#ffffff(call_result, _,
                                                              line, _1, arg4, _2),
          line = arg4
        )
      ),
      Location::Location::getFile_dispred#ff(call_result, f)
    ),
    exists(pure dontcare int _ | stmts(b, _, call_result))
  ),
  exists(pure dontcare Stmt::ControlStructure.class _ |
    EmptyBlock::emptyBlock#ff(_, b)
  )
.
```

**Comment by geoffw0** [comment]
I still can't reproduce poor performance in `lineComment`.

Which branches do you generally work from?  Has the issue manifested on any other machines yet?

**Comment by jbj** [comment]
I tried running the query on 50 or so projects from lgtm.com, and it seemed to be fast. I'm willing to assume that it's just me who got that bad join order with my slightly outdated QL4E and that it'll be fine in the future.

I'm running QL4E 1.18.0 and typically work from the tips of `ql:master` and `code:ql-master`. This is to get the same experience as our external contributors.

**Pull request merged**
