### PR TITLE
C++: add support for custom wide character sizes 

### PR DESCRIPTION
**Pull request by rdmarsh2**
Certain Microsoft projects, such as CoreCLR and ChakraCore, use a
library called the PAL, which enables two-byte strings in the printf
family of functions, even when built on a platform with four-byte
strings. This adds support for determining the size of a wide character
from the definitions of such functions, rather than assuming that they
match the compiler's wchar_t.

### CODE REVIEW

**Comment by jonas-semmle** [comment]
Semmle employees, please see the discussion at https://git.semmle.com/Semmle/public-ql/pull/49

**Comment by jonas-semmle** [comment]
I'd like to have Geoffrey review this if it can wait until next week when he's back from holiday.

**Comment by geoffw0** [comment]
As far as I can tell my comments on https://git.semmle.com/Semmle/public-ql/pull/49 still need responding to.

Also, I think this needs a change note.

**Comment by jbj** [comment]
I'll close this. @geoffw0 has agreed to take over this branch and get it ready for merging.

**Pull request closed without merging**
