### PR TITLE
JavaScript: Autoformat all QL files.

### PR DESCRIPTION
**Pull request by xiemaisi**

### CODE REVIEW

**Comment by xiemaisi** [comment]
Probably best to delay this until after the branching has been sorted out, so marking as WIP.

**Comment by xiemaisi** [comment]
Rebased. With the branching structure now sorted out, I'd be keen on getting this in soon to avoid more pain later on.

**Comment by esben-semmle** [comment]
The `Language-Tests/JavaScript` test failures seem unrelated to the refactoring..

**Comment by xiemaisi** [comment]
Indeed; I'm told the problem that caused the failure is now fixed, so I've retriggered.

**Pull request merged**
