### PR TITLE
Fix typos in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by xiemaisi**

### CODE REVIEW

**Comment by jbj** [comment]
Doesn't it invalidate all CLA agreements if you update this file?

**Comment by xiemaisi** [comment]
No idea; it was last updated yesterday.

**Comment by jf205** [comment]
I also have no idea. Happy to revert the change until we have clarification.

**Comment by xiemaisi** [comment]
Doesn't look like it: https://github.com/Semmle/ql/pull/1720

**Comment by xiemaisi** [comment]
(Or did you mean something else?)

**Pull request merged**
