### PR TITLE
JS: remove false positive in js/missing-space-in-concatenation

### PR DESCRIPTION
**Pull request by erik-krogh**
Fix for #2020 

The fix checks that there is a word-like fragment in the string-concatenation. 

Performance is excellent, but surprisingly it took 2 rounds of dist-compare to get there.

### CODE REVIEW

**Comment by asger-semmle** [comment]
> However, I think the implementation should probably make use of the StringConcationation.qll library,

Seconded, though I'd point to the `StringOps::Concatenation` class and its hierarchy.

**Comment by erik-krogh** [comment]
> for example, there are plenty of two-letter words in the English language, so requiring three alphabetic characters could be considered overly restrictive

Yes, and the updated query will not flag sentences where all the words are of length 1 or 2. As most sentences contain at least one longer word, I think we are OK.

> Seconded, though I'd point to the StringOps::Concatenation class and its hierarchy.

@esben-semmle did initially point me towards StringOps::ConcatenationRoot, and the first iteration of this fix did use that library. 
However, that introduced dataflow, and the query did not previously use any dataflow, thus performance of this query took a massive hit.
That is why I ended up with this purely syntactical alternative.

**Comment by xiemaisi** [comment]
> (...) thus performance of this query took a massive hit.

Right. That doesn't matter, actually. In practice this query will rarely/never be run on its own, it will be run as part of the overall LGTM suite, so the cost of doing dataflow is amortised over all queries. For the purpose of any individual query, you can assume that the its cost is zero.

**Comment by erik-krogh** [comment]
> > (...) thus performance of this query took a massive hit.
> 
> Right. That doesn't matter, actually. In practice this query will rarely/never be run on its own, it will be run as part of the overall LGTM suite, so the cost of doing dataflow is amortised over all queries. For the purpose of any individual query, you can assume that the its cost is zero.

I ran it together with another dataflow query, and yes you're right, the performance difference is negligible.

**Pull request merged**
