### PR TITLE
C++: Add localExprFlow and localExprTaint

### PR DESCRIPTION
**Pull request by jbj**
Cc @lukecartey: this is for https://jira.semmle.com/browse/ODASA-8053.

For comparison, the corresponding PR for Java is #1795.

The `localExprTaint` predicate for IR-based taint tracking will follow in a separate PR.

### CODE REVIEW

**Comment by jbj** [comment]
Change note needs to move to 1.23.

**Comment by jbj** [comment]
Rebased to move change note to 1.23.

**Comment by rdmarsh2** [comment]
Actually, one docs thing I just noticed - `localFlow` is mentioned in the file header comment in `DataFlow.qll`. This should be mentioned there as well.

**Comment by jbj** [comment]
@rdmarsh2 I've added two commits to improve docs.

@semmledocs-ac, can you do doc review on this PR? The QLDoc for the new predicates is mostly copied from either the corresponding predicates in Java or similar predicates around it, so we need to consider consistency if that should change.

**Pull request merged**
