### PR TITLE
JavaScript: Add query for identifying information leak through `postMessage`.

### PR DESCRIPTION
**Pull request by xiemaisi**
This adds a new query that flags calls of the form `w.postMessage(msg, '*')` where `msg` may contain sensitive data.

There are two questions I would particularly appreciate feedback on:

  - Is [CWE-359](https://cwe.mitre.org/data/definitions/359.html) an appropriate classification?
  - Does the set of sources make sense? I went beyond just `SensitiveExpr` to also include credential-like information, using a predicate I found in the C# library. This gives us our only results on the default suite, but I'm not sure they are good results.

For evaluation, I ran the query (in isolation) on our default suite, and then measured the time it took to compute just the query stage; results are [here](https://git.semmle.com/gist/max/ea1433156ecfe68540cfb6f47b4e91cd) (internal link). The numbers towards the bottom of the table look a little high, so I'll re-run the full security suite for those.

There are only two [results](https://git.semmle.com/gist/max/ea1433156ecfe68540cfb6f47b4e91cd#file-results-md) (internal link). Both are on gecko-dev in very similar code, which sends a certificate without origin restriction. I'm not sure whether that's really an interesting result, hence my second question above.

### CODE REVIEW

**Comment by esben-semmle** [comment]
The implementation structure looks like a standard taint query, so that LGTM.

> Is CWE-359 an appropriate classification?

I think [CWE-201: Information Exposure Through Sent Data
](https://cwe.mitre.org/data/definitions/201.html) is a better fit, it is already used in [cs/sensitive-data-transmission](https://github.com/Semmle/ql/blob/54242f40099457f841839bd13bdd65de4c671a33/csharp/ql/src/Security%20Features/CWE-201/ExposureInTransmittedData.ql). Maybe you can use both.

> Does the set of sources make sense? 

Since (cloned) objects can be sent with `postMessage`, it may make sense to also consider the sources in [CleartextLogging.qll](https://github.com/Semmle/ql/blob/54242f40099457f841839bd13bdd65de4c671a33/javascript/ql/src/semmle/javascript/security/dataflow/CleartextLogging.qll), which includes objects with password properties.

**Comment by xiemaisi** [comment]
> I think CWE-201: Information Exposure Through Sent Data is a better fit, it is already used in cs/sensitive-data-transmission. Maybe you can use both.

Done.

> it may make sense to also consider the sources in CleartextLogging.qll, which includes objects with password properties.

Interesting suggestion. Let me look into this, perhaps this is best handled using flow labels.

**Comment by xiemaisi** [comment]
Meanwhile, ping @mc-semmle for doc review.

**Comment by asger-semmle** [comment]
Maybe `authKey` should be considered a credential.

**Comment by xiemaisi** [comment]
> Maybe `authKey` should be considered a credential.

Added. I'll rerun the evaluation with the last few commits included; let me know if there is anything else you'd like to see added.

Meanwhile, my earlier re-run of the security suite on projects where the new query seemed to take a surprisingly long time showed that it is in the same ballpark as `CleartextStorage`, which makes sense, since they have a very similar set of sources:

| Project | CleartextStorage | PostMessageStar |
| --- | :---: | :---: |
| A2Z-F15 | 168 | 169 |
| angular-gulp-webpack-starter | 192 | 110 |
| ChakraCore | 79 | 93 |
| descartes | 63 | 78 |
| gecko-dev | 494 | 538 |
| node | 164 | 106 |

**Comment by asger-semmle** [comment]
Speculating a bit here, but could we possibly get some performance improvements by merging cleartext storage, cleartext logging, and postMessageStar into one query?

**Comment by xiemaisi** [comment]
Worth considering, though at the moment they do have subtly different sources and flow steps (which I'm not sure is a desirable state of affairs).

**Comment by esben-semmle** [comment]
Inspiration for additional sources: 

https://github.com/Semmle/ql/blob/fc5b9dd55e1edf41abbcf250aad85455e91e8c03/javascript/ql/src/semmle/javascript/frameworks/Credentials.qll#L8-L12

You could treat the (local/global) sources of that expression as a source for your query. The other cleartext queries probably want to use that extended source definition as well.

**Comment by xiemaisi** [comment]
Good idea, but perhaps more of a long-term project. Could you add that to the JIRA ticket about improving this group of queries?

**Comment by xiemaisi** [comment]
(Still waiting for doc review.)

**Comment by mc-semmle** [comment]
@xiemaisi - LGTM from an editorial point of view.

**Comment by xiemaisi** [comment]
Thanks, @mc-semmle! @asger-semmle / @esben-semmle, anything else you want me to address?

**Pull request merged**
