### PR TITLE
JS: Add prop names for array element pattern PropReads

### PR DESCRIPTION
**Pull request by asger-semmle**
@max-schaefer do you remember the reason for this being treated as an unknown property?

I'll run an evaluation over the weekend.

### CODE REVIEW

**Comment by max-schaefer** [comment]
Performance, most likely, but it's a good idea to revisit these decisions every once in a while, so an evaluation sounds like an excellent idea.

**Comment by asger-semmle** [comment]
[Evaluation](https://git.semmle.com/asger/dist-compare-reports/tree/element-pattern-prop-read_1573885109863) looks good

**Comment by max-schaefer** [comment]
I'd like to see full evaluation including `gecko-dev` for this if possible, just to rule out any unexpected regression.

**Comment by asger-semmle** [comment]
Starting an evaluation on big-apps

**Comment by asger-semmle** [comment]
[Big-apps evaluation](https://git.semmle.com/asger/dist-compare-reports/tree/element-pattern-prop-read_1574177643899) looks fine

**Pull request merged**
