### PR TITLE
C#: Convert `tests/query-tests/Stubs/Test.cs` to Unix line endings.

### PR DESCRIPTION
**Pull request by xiemaisi**

### CODE REVIEW

**Comment by hvitved** [comment]
I thought `.gitattributes` should take of this automatically?

**Comment by xiemaisi** [comment]
It didn't for me. Do I need to do anything special in order for it to work?

**Comment by dave-bartolomeo** [comment]
@xiemaisi Is it possible that this file was originally committed in a branch that did not yet have the `.gitattributes` changes, then merged into master later?

**Comment by xiemaisi** [comment]
> Is it possible that this file was originally committed in a branch that did not yet have the .gitattributes changes, then merged into master later?

Ah, that must be it. I think this file was introduced by https://github.com/Semmle/ql/tree/593f0a9d71a5bcd2e0b0350c171f15053cb00c47, which only had line ending normalisation for QL files.

**Pull request merged**
