### PR TITLE
C++: Ensure that there is just one overlap for an operand in value numbering

### PR DESCRIPTION
**Pull request by MathiasVP**
It looks like an `Operand` can have multiple `Overlap`s. This makes value numbering assign multiple value numbers to the same instruction, giving rise to a tuple count explosion. This PR filters out those instructions with operands that have multiple `Overlap`s, and removes the tuple count explosion observed in bloomberg/bde.

### CODE REVIEW

**Comment by MathiasVP** [comment]
> I'd rather have us pick the most conservative overlap when there's doubt, preferring `MustTotallyOverlap` over `MustExactlyOverlap`, instead of giving up. We should be able to do that in the SSA construction rather than the value numbering.

I've done this now. Not in a way that I'm very proud of, but it seems to have the same performance characteristics as the original fix.

**Comment by dbartol** [comment]
Unlike many of the other "Thingy has multiple Widgets for some reason" problems we've hit recently, this one seems more likely to be a straightforward bug in either SSA construction or alias analysis, rather than the usual extractor issue caused by the difficulty of pretending to link real-world C++ code. I'd prefer to chase this one down and fix the root cause, but if we don't have time for that, this workaround is as good as any.

**Comment by geoffw0** [comment]
Small observation: all of the cases I've seen (prior to this fix) seem to involve 128-bit values.  Does anything funny go on with those?

**Comment by dbartol** [comment]
@geoffw0 Like `__int128`? Or some vector type? It's possible that code for the IR type system doesn't correctly handle certain esoteric types. Can you point me to a repro?

**Comment by dbartol** [comment]
I did some more digging and found the root cause. There are two definition of the type `BIT_UINT128`:
From `bid_functions.h`:
```c++
typedef struct BID_ALIGN (16)
     {
       BID_UINT64 w[2];
     } BID_UINT128;
```
From `bid_gcc_intrinsics.h`:
```c++
typedef __attribute__ ((aligned(16))) struct
{
  BID_UINT64 w[2];
} BID_UINT128;

```
The `BID_ALIGN (16)` is just a macro that expands to the same `aligned` attribute as the other definition, but note the placement. The first definition puts the attribute after the `struct` keyword, and the second definition puts it before. This seems to be enough to make us treat the two structs slightly differently: One gets treated as an unnamed struct, and the other gets the name `BID_UINT128`. Any function or variable declared with type `BID_UINT128` gets two types, and since the underlying structs are not the same type, they get two separate `IROpaqueType`s as well. That causes the multiple overlaps, because we compute the overlap relationship(s) between all four pairs of `IROpaqueType`s, two of which are `MustExactlyOverlap` and two of which are `MustTotallyOverlap`.

I'm merging this PR because we have no hope for fixing these sorts of database inconsistencies anytime soon.

**Pull request merged**
