### PR TITLE
C++: Update @kind for metric queries

### PR DESCRIPTION
**Pull request by felicity-semmle**
@Semmle/cpp-analysis this PR updates the metric queries to use the alternative `@kind metric` that was introduced by @aibaars in #28231 and #28480. I omitted any deprecated queries.

This seems as if it would be worth doing for 1.19, but if there may be wider implications and you plan to do this later feel free to close the PR.

### CODE REVIEW

**Comment by jbj** [comment]
I have no idea what difference this might make to PI, TI, and LGTM. Are there corresponding PRs for other languages? Who is competent to review this?

**Comment by felicity-semmle** [comment]
Depending on how this PR went, I was planning to make further PRs for other languages.

As far as I know, this is behavior preserving for all products but @aibaars and @adityasharad would be best placed to comment on the safety of this change.

**Comment by adityasharad** [comment]
With Arthur's changes to the toolchain, this is entirely behaviour-preserving for 1.19 onwards, but 1.18 toolchains will not recognise `@kind metric`. With our existing branch-tracking setup, I think this change should either be targeted at `next` now, or at `master` after we release 1.19. @aibaars does that sound sensible?

Another concern I raised on the internal PRs is that the metric property tags still involve `treemap`, e.g. `treemap.warnOn`, because those are a bit harder to rename. So there is a minor oddity of sometimes having `metric` and `treemap` mentioned in the same file, but that's mainly aesthetic.

**Comment by felicity-semmle** [comment]
On balance it sounds as if I should close this PR and raise a couple of Jira issues for consideration in a future release.

**Pull request closed without merging**
