### PR TITLE
C++: Fix join order in def-by-reference data flow

### PR DESCRIPTION
**Pull request by jbj**
This PR fixes a regression introduced in #1000.

The performance was adequate on most projects but degenerated on https://github.com/Microsoft/Tocino.

### CODE REVIEW

**Comment by jbj** [comment]
This also affects nsnam/ns-3-dev-git.

**Comment by jbj** [comment]
From a practical point of view, I've tested the change on the two problematic projects, and the performance issue went away. From a theoretical point of view, the `or ...` section that's added can't contribute more tuples than the number of definitions by reference in the program times the average number of CFG predecessors they have (should be very close to one).

**Comment by geoffw0** [comment]
OK, I'll give it a quick spin myself (this is for the RC branch after all) and then merge.

**Comment by geoffw0** [comment]
Seems fine.  Merging.

**Pull request merged**
