### PR TITLE
.gitignore everything under .vs in repo root dir

### PR DESCRIPTION
**Pull request by jbj**
We have external users editing queries with Visual Studio, and it seems to automatically add very specific files to `.gitignore`. These changes cause conflicts between unrelated PRs.

This commit adds all of `/.vs` to `.gitignore`, which should hopfully make Visual Studio stop adding more entries.

@raulgarciamsft FYI.

### CODE REVIEW

**Comment by adityasharad** [comment]
Could you please add `!**/.vs/VSWorkspaceSettings.json` below that? Those files are checked into the repository for use in QL for VS, and so should be tracked.

**Comment by jbj** [comment]
@adityasharad The pattern I added only ignores a `.vs` dir at the root of the repo (it's prefixed with `/`). The `VSWorkspaceSettings.json` are all in subdirs. Do you want to track `.vs/VSWorkspaceSettings.json` at the root in case such a file should appear there in the future?

**Comment by adityasharad** [comment]
I think it is a good idea to track such a file at the root, I do plan to add it in future.

I see that your pattern only applies to the root, but I think it's worth extending it so that it applies to all the nested `.vs` folders too, otherwise a user who opens a subfolder in VS doesn't benefit from this PR.

**Comment by jbj** [comment]
I've added patterns to that effect. I validated them by creating `.vs/unrelated` and observing that this didn't cause `git status` to display anything, then adding `.vs/VSWorkspaceSettings.json` and observing that this caused `git status` to display `.vs/` under _Untracked files_. I couldn't get it to display the file itself, only the `.vs/` dir.

**Pull request merged**
