### PR TITLE
C++: enable the QL-based CFG code

### PR DESCRIPTION
**Pull request by jbj**
~I've made this a draft PR because we need #2066 merged first. But it's ready for review.~

I've tested this as follows
- CPP-Differences (job 577) showed no differences.
- [Distribution builds](https://lgtm.com/admin/dist_builds/?create_time=1569998153481&had_default_dist=true) (with #2066) showed no new timeouts.
- [Distribution build performance stats](https://lgtm.com/admin/dist_builds/migration/?create_time=1569998153481) showed a 5% slowdown (7.46 / 145.32), which I think is acceptable. I tested the outliers in QL4E, and I didn't find anything pathological about their slowdown.
- I've run [`tellDifferent.ql`](https://github.com/Semmle/ql/blob/master/cpp/ql/test/library-tests/syntax-zoo/tellDifferent.ql) on several snapshots to see the differences between the QL-based CFG and the extractor-based CFG. The issues I've found are linked from CPP-257, and I don't think any of them are blockers.

### CODE REVIEW

**Comment by jbj** [comment]
Added 3 commits to fix the failing qltests.

**Comment by rdmarsh2** [comment]
Were there any test changes associated with the `if constexpr` commit?

**Comment by jbj** [comment]
@rdmarsh2 Yes -- the test referred to in the commit message (41d344a8b7b8d0f5bc7af57031842dfb9d59edae).

**Comment by jbj** [comment]
I have the alert changes from the lgtm.com dist build: https://semmle.slack.com/archives/C0UESAX0T/p1570626576009600?thread_ts=1570621624.005300&cid=C0UESAX0T. I'll try to analyse them tomorrow.

**Comment by geoffw0** [comment]
I just ran some ad-hoc query tests on a local snapshot - no problems, but performance was ~30% worse, rather than 5% worse.  The largest new predicates computed appear to be `CFG::normalGroupMember` and `CFG::subEdge`.  I haven't tested nearly as thoroughly as you, but I'd like to know more about performance.

**Comment by jbj** [comment]
The number 5% is for the whole LGTM suite. The CFG is only computed once in the whole suite, so 5% is a pretty big increase. If you look at one query only, from a cold cache, you'll easily hit 30%. If you pick just the right query, it might be over 50%.

There might be room for improvement. In particular, I think it's possible to restructure `CFG::subEdge` such that it can be split across multiple threads. There might also be some performance to gain from turning the `newtype`s into classes that extend `int`, but if it's not a lot of performance then I'd prefer the clarity that comes with `newtype`s.

**Comment by geoffw0** [comment]
> I have the alert changes from the lgtm.com dist build: https://semmle.slack.com/archives/C0UESAX0T/p1570626576009600?thread_ts=1570621624.005300&cid=C0UESAX0T. I'll try to analyse them tomorrow.

Have you looked at these?  I'm going to try and figure out what happened to `cpp/missing-return` (many new results), `cpp/futile-params` (all results lost) and `cpp/nested-loops-with-same-variable` (all results lost) later today.

**Comment by jbj** [comment]
I didn't get to this today, so it's great if you'll investigate. The `cpp/missing-return` query in particular is an excellent canary in the coal mine for CFG problems.

**Comment by geoffw0** [comment]
Most/all of the `cpp/missing-return` problems are caused by a failure to extract `__builtin_complex` correctly.  I tried to write a test but it just reports invalid keys and fails (reporting an extractor error) whenever I use `__builtin_complex`, even with various combinations of flags and `--expect_errors`.  We have examples on LGTM (such as https://lgtm.com/projects/g/endrazine/wcc) where similar code appears to have been extracted successfully (though I'm not sure about actually correctly).  I'm stuck for what to do next, other than wait for @nickrolfe to come up with an extractor fix.

I believe a suitable test for `cpp/missing-return` would be:
```
#define complex _Complex

complex float test1(float a, float b)
{
	return __builtin_complex(a, b); // GOOD
}

complex float test2(float a, float b)
{
	complex float x = __builtin_complex(a, b); // BAD (missing return statement)
}
```
but we probably also want library test coverage for `__builtin_complex`.

I haven't looked into `cpp/futile-params` or `cpp/nested-loops-with-same-variable` yet and, to be honest, it's not going to happen soon (on the positive side they're less serious and I would be prepared to merge this and worry about them afterwards).

**Comment by nickrolfe** [comment]
#2115 and the corresponding extractor PR will hopefully provide the fix you need.

**Comment by jbj** [comment]
There's something fishy about those alert diff counts. They're supposed to compare the same commit for the two dists, so I can't explain why the `cpp/fixme-comment` counts change. That query does not depend on the CFG -- I've checked the DIL.

**Comment by geoffw0** [comment]
> There's something fishy about those alert diff counts.

Any further thoughts on this?  Do you think this is mergeable once https://github.com/Semmle/ql/pull/2115 is in?

**Comment by jbj** [comment]
I'd like to investigate these two first:

```
com.lgtm/cpp-queries:cpp/futile-params: 55 -> 0 = -55
com.lgtm/cpp-queries:cpp/mistyped-function-arguments: 0 -> 9 = 9
```

**Comment by jbj** [comment]
Okay, neither of those queries have anything to do with the CFG. The 55 lost results in `cpp/futile-params` all come from g/mono/mono, and I've checked locally that they're lost in that snapshot even without the CFG change. I think what we're seeing is just all the wobble on lgtm.com caused by non-deterministic builds.

So now I think this PR is safe to merge.

**Comment by geoffw0** [comment]
I've created https://github.com/Semmle/ql/pull/2141 as confirmation that we can expect `cpp/missing-return` to work (the `__builtin_complex` issue) - and in fact the issue had little to do with this PR.

**Pull request merged**
