### PR TITLE
Setting a SECURITY_DESCRIPTOR’s DACL to NULL

### PR DESCRIPTION
**Pull request by raulgarciamsft**
Closing the gap between Semmle & PreFAST
This rule is equivalent to C6248

### CODE REVIEW

**Comment by jbj** [comment]
There are some Unicode curly apostrophes (’ instead of ') in this PR that's causing our tests to fail due to platform differences. Please rebase to remove them from the git history.

I've spotted them in the following places
- The commit message of the first commit.
- The `@name` and `@description` of the query.
- The two alert messages of the query.
- In the `UnsafeDaclSecurityDescriptor.expected` file, where they've been encoded as `\u2019`.

**Comment by jbj** [comment]
I just noticed that some files use a mix of tabs and spaces. Sorry, but we have a CI check for that that only runs internally and not on external PRs. It'll start failing if we merge this. Please change tabs to spaces in all files.

Apart from that, this PR looks great, and I'll be happy to merge it. Thanks for the detailed help text and tests.

**Comment by jbj** [comment]
The tests are failing after 925c3b51f9a601c6d1e84ed617bf8e158d8a863c because all the line numbers in the `expected` file need to move down by one.

**Comment by raulgarciamsft** [comment]
Fixing the .expected file and a few more tabs that I found.

**Comment by jbj** [comment]
The last fix to the `expected` file re-introduced to `\u2019`, which is why the test is failing now.

There's also now a conflict in `.gitignore` after I merged your other PR. I'm not sure where those `.gitignore` changes are coming from, but maybe we should just ignore all of `/.vs`?

**Comment by raulgarciamsft** [comment]
Thanks… I have to find out why VS is changing the ' to ‘ … in the meantime I will try to get rid of them in the text.

**Comment by raulgarciamsft** [comment]
Thanks a lot

**Pull request merged**
