### PR TITLE
C#: Update `@name` for two queries

### PR DESCRIPTION
**Pull request by hvitved**

### CODE REVIEW

**Comment by aibaars** [comment]
@felicity-semmle @hvitved This also requires a change to the change notes, right?

**Comment by hvitved** [comment]
> This also requires a change to the change notes, right?

Shouldn't be needed; these queries were added in 1.21.

**Comment by aibaars** [comment]
Well adding a new query is also a change ... 
See https://github.com/Semmle/ql/pull/1501

**Comment by hvitved** [comment]
> Well adding a new query is also a change

You are right, forgot about that.

**Comment by felicity-semmle** [comment]
This also change needs a PR to update the change notes in the code repository...

**Comment by felicity-semmle** [comment]
All LGTM. Thanks for the correction.

**Pull request merged**
