### PR TITLE
Merge master into rc/1.20

### PR DESCRIPTION
**Pull request by xiemaisi**
Not something we usually do, but needed in this case to pull in PRs that were meant for rc/1.20 but got left behind when the RC branch was created.

### CODE REVIEW

**Comment by jbj** [comment]
LGTM. This pulls #1012 into 1.20, which is where it belongs because the corresponding internal PR was merged into 1.20.

**Comment by markshannon** [comment]
LGTM as far as the Python changes are concerned.

**Comment by jbj** [comment]
@xiemaisi You've opened the PR directly from `master`. The tests will never complete as they're restarted on every merge to `master`.

(I'd be totally fine with having the merge of #1024 in 1.20).

**Comment by xiemaisi** [comment]
Replaced by https://github.com/Semmle/ql/pull/1032.

**Pull request closed without merging**
