### PR TITLE
Python: Modernise the `py/explicit-return-in-init` query. 

### PR DESCRIPTION
**Pull request by RasmusWL**

### CODE REVIEW

**Comment by RasmusWL** [comment]
Rebased this branch after merging #1961

**Comment by RasmusWL** [comment]
Running the new and improved query here: https://lgtm.com/query/8916484868186951346/

Results from the original: https://lgtm.com/query/5042346687305091535/

**Comment by RasmusWL** [comment]
By using the new query with `pointTo` analysis to check if the return value is None: results found in 43 projects. Before, results found in 45 projects.

Some of them are still not desirable. For example
1. [`ret = super().__init__(); return ret`](https://lgtm.com/projects/g/ifwe/digsby/snapshot/f968a754ebdf287ef030bcac5d76c22f152cc077/files/digsby/src/gui/pref/pg_accounts.py?sort=name&dir=ASC&mode=heatmap#x800fe62c82f1ec23:1)
2. [`log = logging.getLogger(); return log.error()`](https://lgtm.com/projects/b/jjburton/cgmtools/snapshot/0d8a429b7ea17854a5e5341df98b1cbd54d7fe6c/files/mayaTools/cgm/core/mrs/RigBlocks.py?sort=name&dir=ASC&mode=heatmap#x5cff571b318110a6:1)

Should we do anything about these before we merge?

**Comment by taus-semmle** [comment]
Oh, as for the two results you point out, I think it's fine to leave them in. Even if they won't cause problems during runtime, it _is_ still superfluous (and potentially confusing) to use a `return` statement in those places.

**Pull request merged**
