### PR TITLE
LF all the things

### PR DESCRIPTION
**Pull request by dave-bartolomeo**
This change forces LF line endings for pretty much every text file in the repo. I added a few more directory-specific .gitattributes files for text files that need to have CRLF line endings, but everything else is LF now.

### CODE REVIEW

**Comment by esben-semmle** [comment]
JavaScript changes :+1:

**Comment by jbj** [comment]
@dave-bartolomeo for sanity checking, please compare this to #181, which does something very similar. The first thing I notice is that #181 removes CRs in extensionless files like `cpp/config/suites/security/cwe-120` whereas this PR doesn't.

**Comment by dave-bartolomeo** [comment]
I've updated .gitattributes to just use `* text=auto eol=lf`, so all text files are now normalized.

**Comment by dave-bartolomeo** [comment]
Anybody from @Semmle/cs and @Semmle/java want to take a quick look?

**Comment by aschackmull** [comment]
Looks like the java changes just hit example files for qhelp, so that LGTM.

**Pull request merged**
